/*
 * generated by Xtext 2.15.0
 */
package it.univaq.disim.typhon.ide


/**
 * Use this class to register ide components.
 */
class TyphonMLIdeModule extends AbstractTyphonMLIdeModule {
}
