<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="typhonmlreq" nsPrefix="typhonmlreq" nsURI="http://org.typhon.dsls.typhonml.req" xmi:version="2.0">
  <eClassifiers abstract="true" name="NamedElement" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" lowerBound="1" name="name" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" name="importedNamespace" xsi:type="ecore:EAttribute"/>
  </eClassifiers>
  <eClassifiers name="ModelReq" xsi:type="ecore:EClass">
    <eStructuralFeatures containment="true" eType="#//DBType" name="dbTypes" upperBound="-1" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eType="#//FRequirement" name="frequirements" upperBound="-1" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eType="#//NFRequirement" name="nfrequirements" upperBound="-1" xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//NamedElement" name="DBType" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="#//FRequirement" name="frequirements" upperBound="-1" xsi:type="ecore:EReference"/>
    <eStructuralFeatures eType="#//NFRequirement" name="nfrequirements" upperBound="-1" xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//NamedElement" name="FRequirement" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" lowerBound="1" name="description" xsi:type="ecore:EAttribute"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//NamedElement" name="NFRequirement" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" lowerBound="1" name="description" xsi:type="ecore:EAttribute"/>
  </eClassifiers>
</ecore:EPackage>
