<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="typhonmltag" nsURI="http://org.typhon.dsls.typhonml.tag" nsPrefix="typhonmltag">
  <eClassifiers xsi:type="ecore:EClass" name="ModelTag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityTags" upperBound="-1"
        eType="#//EntityTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalRequirements"
        upperBound="-1" eType="#//FunctionalTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nfunctionalRequirements"
        upperBound="-1" eType="#//NFunctionalTag" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityTag" eSuperTypes="../../it.univaq.disim.typhonml/model/typhonml.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalTag" upperBound="-1"
        eType="#//FunctionalTag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nfunctionalTag" upperBound="-1"
        eType="#//NFunctionalTag"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NFunctionalTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
