/**
 * generated by Xtext 2.15.0
 */
package it.univaq.disim.typhon.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.univaq.disim.typhon.TyphonMLRuntimeModule;
import it.univaq.disim.typhon.TyphonMLStandaloneSetup;
import it.univaq.disim.typhon.ide.TyphonMLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TyphonMLIdeSetup extends TyphonMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    TyphonMLRuntimeModule _typhonMLRuntimeModule = new TyphonMLRuntimeModule();
    TyphonMLIdeModule _typhonMLIdeModule = new TyphonMLIdeModule();
    return Guice.createInjector(Modules2.mixin(_typhonMLRuntimeModule, _typhonMLIdeModule));
  }
}
