/**
 * generated by Xtext 2.15.0
 */
package it.univaq.disim.typhon.ui;

import it.univaq.disim.typhon.ui.AbstractTyphonMLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TyphonMLUiModule extends AbstractTyphonMLUiModule {
  public TyphonMLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
