/**
 * generated by Xtext 2.12.0
 */
package org.typhon.dsls.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.typhon.dsls.xtext.ui.AbstractTyphonMLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TyphonMLUiModule extends AbstractTyphonMLUiModule {
  public TyphonMLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
