/**
 * generated by Xtext 2.12.0
 */
package org.typhon.dsls.xtext.scoping;

import org.typhon.dsls.xtext.scoping.AbstractTyphonMLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TyphonMLScopeProvider extends AbstractTyphonMLScopeProvider {
}
