/**
 * generated by Xtext 2.12.0
 */
package org.typhon.dsls.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.typhon.dsls.xtext.TyphonMLRuntimeModule;
import org.typhon.dsls.xtext.TyphonMLStandaloneSetup;
import org.typhon.dsls.xtext.ide.TyphonMLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TyphonMLIdeSetup extends TyphonMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    TyphonMLRuntimeModule _typhonMLRuntimeModule = new TyphonMLRuntimeModule();
    TyphonMLIdeModule _typhonMLIdeModule = new TyphonMLIdeModule();
    return Guice.createInjector(Modules2.mixin(_typhonMLRuntimeModule, _typhonMLIdeModule));
  }
}
