/**
 * generated by Xtext 2.12.0
 */
package org.typhon.dsls.xtext.ide;

import org.typhon.dsls.xtext.ide.AbstractTyphonMLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TyphonMLIdeModule extends AbstractTyphonMLIdeModule {
}
