/**
 * generated by Xtext 2.12.0
 */
package org.typhon.dsls.xtext.ui.contentassist;

import org.typhon.dsls.xtext.ui.contentassist.AbstractTyphonMLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TyphonMLProposalProvider extends AbstractTyphonMLProposalProvider {
}
