/*
 * generated by Xtext 2.19.0
 */
package it.univaq.disim.typhon.ui.tests;

import com.google.inject.Injector;
import it.univaq.disim.typhonml.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TyphonMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("it.univaq.disim.typhon.TyphonML");
	}

}
