/*
 * generated by Xtext 2.20.0
 */
package it.univaq.disim.typhon.serializer;

import com.google.inject.Inject;
import it.univaq.disim.typhon.services.TyphonMLGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import typhonml.AddAttributesToIndex;
import typhonml.AddCollectionIndex;
import typhonml.AddCustomDataTypeAttribute;
import typhonml.AddEntity;
import typhonml.AddGraphAttribute;
import typhonml.AddGraphEdge;
import typhonml.AddIndex;
import typhonml.AddRelation;
import typhonml.Attribute;
import typhonml.BigintType;
import typhonml.BlobType;
import typhonml.BoolType;
import typhonml.ChangeCustomDataTypeAttribute;
import typhonml.ChangePrimitiveDataTypeAttribute;
import typhonml.ChangeRelationCardinality;
import typhonml.ChangeRelationContainement;
import typhonml.Collection;
import typhonml.Column;
import typhonml.ColumnDB;
import typhonml.CustomAttribute;
import typhonml.CustomDataType;
import typhonml.CustomDataTypeImplementationPackage;
import typhonml.CustomDataTypeItem;
import typhonml.DateType;
import typhonml.DatetimeType;
import typhonml.DisableBidirectionalRelation;
import typhonml.DisableRelationContainment;
import typhonml.DocumentDB;
import typhonml.DropCollectionIndex;
import typhonml.DropIndex;
import typhonml.EnableBidirectionalRelation;
import typhonml.EnableRelationContainment;
import typhonml.Entity;
import typhonml.FloatType;
import typhonml.FreetextType;
import typhonml.FunctionalTag;
import typhonml.GraphAttribute;
import typhonml.GraphDB;
import typhonml.GraphEdge;
import typhonml.GraphEdgeLabel;
import typhonml.GraphNode;
import typhonml.IdSpec;
import typhonml.IndexSpec;
import typhonml.IntType;
import typhonml.KeyValueDB;
import typhonml.KeyValueElement;
import typhonml.MergeEntity;
import typhonml.MigrateEntity;
import typhonml.Model;
import typhonml.NFunctionalTag;
import typhonml.NlpTask;
import typhonml.PointType;
import typhonml.PolygonType;
import typhonml.Relation;
import typhonml.RelationalDB;
import typhonml.RemoveAttribute;
import typhonml.RemoveAttributesToIndex;
import typhonml.RemoveEntity;
import typhonml.RemoveGraphAttribute;
import typhonml.RemoveGraphEdge;
import typhonml.RemoveRelation;
import typhonml.RenabeGraphEdgeLabel;
import typhonml.RenameAttribute;
import typhonml.RenameCollection;
import typhonml.RenameEntity;
import typhonml.RenameRelation;
import typhonml.RenameTable;
import typhonml.SplitEntity;
import typhonml.SplitEntityHorizontal;
import typhonml.SplitEntityVertical;
import typhonml.StringType;
import typhonml.Table;
import typhonml.TextType;
import typhonml.TyphonmlPackage;

@SuppressWarnings("all")
public class TyphonMLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private TyphonMLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == TyphonmlPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case TyphonmlPackage.ADD_ATTRIBUTES_TO_INDEX:
				sequence_AddAttributesToIndex(context, (AddAttributesToIndex) semanticObject); 
				return; 
			case TyphonmlPackage.ADD_COLLECTION_INDEX:
				sequence_AddCollectionIndex(context, (AddCollectionIndex) semanticObject); 
				return; 
			case TyphonmlPackage.ADD_CUSTOM_DATA_TYPE_ATTRIBUTE:
				sequence_AddCustomDataTypeAttribute(context, (AddCustomDataTypeAttribute) semanticObject); 
				return; 
			case TyphonmlPackage.ADD_ENTITY:
				sequence_AddEntity(context, (AddEntity) semanticObject); 
				return; 
			case TyphonmlPackage.ADD_GRAPH_ATTRIBUTE:
				sequence_AddGraphAttribute(context, (AddGraphAttribute) semanticObject); 
				return; 
			case TyphonmlPackage.ADD_GRAPH_EDGE:
				sequence_AddGraphEdge(context, (AddGraphEdge) semanticObject); 
				return; 
			case TyphonmlPackage.ADD_INDEX:
				if (rule == grammarAccess.getAddIndexTableRule()) {
					sequence_AddIndexTable(context, (AddIndex) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getChangeOperatorRule()
						|| rule == grammarAccess.getAddIndexRule()) {
					sequence_AddIndex(context, (AddIndex) semanticObject); 
					return; 
				}
				else break;
			case TyphonmlPackage.ADD_RELATION:
				sequence_AddRelation(context, (AddRelation) semanticObject); 
				return; 
			case TyphonmlPackage.ATTRIBUTE:
				sequence_Attribute_Impl(context, (Attribute) semanticObject); 
				return; 
			case TyphonmlPackage.BIGINT_TYPE:
				sequence_BigintType(context, (BigintType) semanticObject); 
				return; 
			case TyphonmlPackage.BLOB_TYPE:
				sequence_BlobType(context, (BlobType) semanticObject); 
				return; 
			case TyphonmlPackage.BOOL_TYPE:
				sequence_BoolType(context, (BoolType) semanticObject); 
				return; 
			case TyphonmlPackage.CHANGE_CUSTOM_DATA_TYPE_ATTRIBUTE:
				sequence_ChangeCustomDataTypeAttribute(context, (ChangeCustomDataTypeAttribute) semanticObject); 
				return; 
			case TyphonmlPackage.CHANGE_PRIMITIVE_DATA_TYPE_ATTRIBUTE:
				sequence_ChangePrimitiveDataTypeAttribute(context, (ChangePrimitiveDataTypeAttribute) semanticObject); 
				return; 
			case TyphonmlPackage.CHANGE_RELATION_CARDINALITY:
				sequence_ChangeRelationCardinality(context, (ChangeRelationCardinality) semanticObject); 
				return; 
			case TyphonmlPackage.CHANGE_RELATION_CONTAINEMENT:
				sequence_ChangeRelationContainement(context, (ChangeRelationContainement) semanticObject); 
				return; 
			case TyphonmlPackage.COLLECTION:
				sequence_Collection(context, (Collection) semanticObject); 
				return; 
			case TyphonmlPackage.COLUMN:
				sequence_Column(context, (Column) semanticObject); 
				return; 
			case TyphonmlPackage.COLUMN_DB:
				sequence_ColumnDB(context, (ColumnDB) semanticObject); 
				return; 
			case TyphonmlPackage.CUSTOM_ATTRIBUTE:
				sequence_CustomAttribute(context, (CustomAttribute) semanticObject); 
				return; 
			case TyphonmlPackage.CUSTOM_DATA_TYPE:
				sequence_CustomDataType(context, (CustomDataType) semanticObject); 
				return; 
			case TyphonmlPackage.CUSTOM_DATA_TYPE_IMPLEMENTATION_PACKAGE:
				sequence_CustomDataTypeImplementationPackage(context, (CustomDataTypeImplementationPackage) semanticObject); 
				return; 
			case TyphonmlPackage.CUSTOM_DATA_TYPE_ITEM:
				sequence_CustomDataTypeItem(context, (CustomDataTypeItem) semanticObject); 
				return; 
			case TyphonmlPackage.DATE_TYPE:
				sequence_DateType(context, (DateType) semanticObject); 
				return; 
			case TyphonmlPackage.DATETIME_TYPE:
				sequence_DatetimeType(context, (DatetimeType) semanticObject); 
				return; 
			case TyphonmlPackage.DISABLE_BIDIRECTIONAL_RELATION:
				sequence_DisableBidirectionalRelation(context, (DisableBidirectionalRelation) semanticObject); 
				return; 
			case TyphonmlPackage.DISABLE_RELATION_CONTAINMENT:
				sequence_DisableRelationContainment(context, (DisableRelationContainment) semanticObject); 
				return; 
			case TyphonmlPackage.DOCUMENT_DB:
				sequence_DocumentDB(context, (DocumentDB) semanticObject); 
				return; 
			case TyphonmlPackage.DROP_COLLECTION_INDEX:
				sequence_DropCollectionIndex(context, (DropCollectionIndex) semanticObject); 
				return; 
			case TyphonmlPackage.DROP_INDEX:
				if (rule == grammarAccess.getDropIndexTableRule()) {
					sequence_DropIndexTable(context, (DropIndex) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getChangeOperatorRule()
						|| rule == grammarAccess.getDropIndexRule()) {
					sequence_DropIndex(context, (DropIndex) semanticObject); 
					return; 
				}
				else break;
			case TyphonmlPackage.ENABLE_BIDIRECTIONAL_RELATION:
				sequence_EnableBidirectionalRelation(context, (EnableBidirectionalRelation) semanticObject); 
				return; 
			case TyphonmlPackage.ENABLE_RELATION_CONTAINMENT:
				sequence_EnableRelationContainment(context, (EnableRelationContainment) semanticObject); 
				return; 
			case TyphonmlPackage.ENTITY:
				sequence_Entity_Impl(context, (Entity) semanticObject); 
				return; 
			case TyphonmlPackage.FLOAT_TYPE:
				sequence_FloatType(context, (FloatType) semanticObject); 
				return; 
			case TyphonmlPackage.FREETEXT_TYPE:
				sequence_FreetextType(context, (FreetextType) semanticObject); 
				return; 
			case TyphonmlPackage.FUNCTIONAL_TAG:
				sequence_FunctionalTag_Impl(context, (FunctionalTag) semanticObject); 
				return; 
			case TyphonmlPackage.GRAPH_ATTRIBUTE:
				sequence_GraphAttribute_Impl(context, (GraphAttribute) semanticObject); 
				return; 
			case TyphonmlPackage.GRAPH_DB:
				sequence_GraphDB(context, (GraphDB) semanticObject); 
				return; 
			case TyphonmlPackage.GRAPH_EDGE:
				sequence_GraphEdge_Impl(context, (GraphEdge) semanticObject); 
				return; 
			case TyphonmlPackage.GRAPH_EDGE_LABEL:
				sequence_GraphEdgeLabel(context, (GraphEdgeLabel) semanticObject); 
				return; 
			case TyphonmlPackage.GRAPH_NODE:
				sequence_GraphNode(context, (GraphNode) semanticObject); 
				return; 
			case TyphonmlPackage.ID_SPEC:
				sequence_IdSpec(context, (IdSpec) semanticObject); 
				return; 
			case TyphonmlPackage.INDEX_SPEC:
				sequence_IndexSpec(context, (IndexSpec) semanticObject); 
				return; 
			case TyphonmlPackage.INT_TYPE:
				sequence_IntType(context, (IntType) semanticObject); 
				return; 
			case TyphonmlPackage.KEY_VALUE_DB:
				sequence_KeyValueDB(context, (KeyValueDB) semanticObject); 
				return; 
			case TyphonmlPackage.KEY_VALUE_ELEMENT:
				sequence_KeyValueElement(context, (KeyValueElement) semanticObject); 
				return; 
			case TyphonmlPackage.MERGE_ENTITY:
				sequence_MergeEntity(context, (MergeEntity) semanticObject); 
				return; 
			case TyphonmlPackage.MIGRATE_ENTITY:
				sequence_MigrateEntity(context, (MigrateEntity) semanticObject); 
				return; 
			case TyphonmlPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case TyphonmlPackage.NFUNCTIONAL_TAG:
				sequence_NFunctionalTag_Impl(context, (NFunctionalTag) semanticObject); 
				return; 
			case TyphonmlPackage.NLP_TASK:
				sequence_NlpTask(context, (NlpTask) semanticObject); 
				return; 
			case TyphonmlPackage.POINT_TYPE:
				sequence_PointType(context, (PointType) semanticObject); 
				return; 
			case TyphonmlPackage.POLYGON_TYPE:
				sequence_PolygonType(context, (PolygonType) semanticObject); 
				return; 
			case TyphonmlPackage.RELATION:
				sequence_Relation_Impl(context, (Relation) semanticObject); 
				return; 
			case TyphonmlPackage.RELATIONAL_DB:
				sequence_RelationalDB(context, (RelationalDB) semanticObject); 
				return; 
			case TyphonmlPackage.REMOVE_ATTRIBUTE:
				sequence_RemoveAttribute(context, (RemoveAttribute) semanticObject); 
				return; 
			case TyphonmlPackage.REMOVE_ATTRIBUTES_TO_INDEX:
				sequence_RemoveAttributesToIndex(context, (RemoveAttributesToIndex) semanticObject); 
				return; 
			case TyphonmlPackage.REMOVE_ENTITY:
				sequence_RemoveEntity(context, (RemoveEntity) semanticObject); 
				return; 
			case TyphonmlPackage.REMOVE_GRAPH_ATTRIBUTE:
				sequence_RemoveGraphAttribute(context, (RemoveGraphAttribute) semanticObject); 
				return; 
			case TyphonmlPackage.REMOVE_GRAPH_EDGE:
				sequence_RemoveGraphEdge(context, (RemoveGraphEdge) semanticObject); 
				return; 
			case TyphonmlPackage.REMOVE_RELATION:
				sequence_RemoveRelation(context, (RemoveRelation) semanticObject); 
				return; 
			case TyphonmlPackage.RENABE_GRAPH_EDGE_LABEL:
				sequence_RenabeGraphEdgeLabel(context, (RenabeGraphEdgeLabel) semanticObject); 
				return; 
			case TyphonmlPackage.RENAME_ATTRIBUTE:
				sequence_RenameAttribute(context, (RenameAttribute) semanticObject); 
				return; 
			case TyphonmlPackage.RENAME_COLLECTION:
				sequence_RenameCollection(context, (RenameCollection) semanticObject); 
				return; 
			case TyphonmlPackage.RENAME_ENTITY:
				sequence_RenameEntity(context, (RenameEntity) semanticObject); 
				return; 
			case TyphonmlPackage.RENAME_RELATION:
				sequence_RenameRelation(context, (RenameRelation) semanticObject); 
				return; 
			case TyphonmlPackage.RENAME_TABLE:
				sequence_RenameTable(context, (RenameTable) semanticObject); 
				return; 
			case TyphonmlPackage.SPLIT_ENTITY:
				sequence_SplitEntity(context, (SplitEntity) semanticObject); 
				return; 
			case TyphonmlPackage.SPLIT_ENTITY_HORIZONTAL:
				sequence_SplitEntityHorizontal(context, (SplitEntityHorizontal) semanticObject); 
				return; 
			case TyphonmlPackage.SPLIT_ENTITY_VERTICAL:
				sequence_SplitEntityVertical(context, (SplitEntityVertical) semanticObject); 
				return; 
			case TyphonmlPackage.STRING_TYPE:
				sequence_StringType(context, (StringType) semanticObject); 
				return; 
			case TyphonmlPackage.TABLE:
				sequence_Table(context, (Table) semanticObject); 
				return; 
			case TyphonmlPackage.TEXT_TYPE:
				sequence_TextType(context, (TextType) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     ChangeOperator returns AddAttributesToIndex
	 *     AddAttributesToIndex returns AddAttributesToIndex
	 *
	 * Constraint:
	 *     (table=[Table|EString] attributes+=[Attribute|EString] attributes+=[Attribute|EString]?)
	 */
	protected void sequence_AddAttributesToIndex(ISerializationContext context, AddAttributesToIndex semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns AddCollectionIndex
	 *     AddCollectionIndex returns AddCollectionIndex
	 *
	 * Constraint:
	 *     (collection=[Collection|EString] (attributes+=[Attribute|EString] attributes+=[Attribute|EString]*)?)
	 */
	protected void sequence_AddCollectionIndex(ISerializationContext context, AddCollectionIndex semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Attribute returns AddCustomDataTypeAttribute
	 *     EntityAttribute returns AddCustomDataTypeAttribute
	 *     ChangeOperator returns AddCustomDataTypeAttribute
	 *     AddCustomDataTypeAttribute returns AddCustomDataTypeAttribute
	 *
	 * Constraint:
	 *     (name=EString importedNamespace=EString? ownerEntity=[Entity|EString] type=CustomDataType)
	 */
	protected void sequence_AddCustomDataTypeAttribute(ISerializationContext context, AddCustomDataTypeAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns AddEntity
	 *     AddEntity returns AddEntity
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString (attributes+=Attribute attributes+=Attribute*)* (relations+=AddRelation relations+=AddRelation*)*)
	 */
	protected void sequence_AddEntity(ISerializationContext context, AddEntity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GraphAttribute returns AddGraphAttribute
	 *     ChangeOperator returns AddGraphAttribute
	 *     AddGraphAttribute returns AddGraphAttribute
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString value=[Attribute|EString]?)
	 */
	protected void sequence_AddGraphAttribute(ISerializationContext context, AddGraphAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GraphEdge returns AddGraphEdge
	 *     ChangeOperator returns AddGraphEdge
	 *     AddGraphEdge returns AddGraphEdge
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString from=[GraphNode|EString]? to=[GraphNode|EString]? (labels+=GraphEdgeLabel labels+=GraphEdgeLabel*)?)
	 */
	protected void sequence_AddGraphEdge(ISerializationContext context, AddGraphEdge semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AddIndexTable returns AddIndex
	 *
	 * Constraint:
	 *     (table=[Table|EString] attributes+=[Attribute|EString] attributes+=[Attribute|EString]?)
	 */
	protected void sequence_AddIndexTable(ISerializationContext context, AddIndex semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns AddIndex
	 *     AddIndex returns AddIndex
	 *
	 * Constraint:
	 *     (table=[Table|EString] (attributes+=[Attribute|EString] attributes+=[Attribute|EString]*)?)
	 */
	protected void sequence_AddIndex(ISerializationContext context, AddIndex semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns AddRelation
	 *     AddRelation returns AddRelation
	 *
	 * Constraint:
	 *     (
	 *         importedNamespace=EString? 
	 *         name=EString 
	 *         ownerEntity=[Entity|EString] 
	 *         isContainment?=':'? 
	 *         type=[Entity|EString] 
	 *         opposite=[Relation|EString]? 
	 *         cardinality=Cardinality?
	 *     )
	 */
	protected void sequence_AddRelation(ISerializationContext context, AddRelation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Attribute returns Attribute
	 *     EntityAttribute returns Attribute
	 *     Attribute_Impl returns Attribute
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString type=DataType)
	 */
	protected void sequence_Attribute_Impl(ISerializationContext context, Attribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns BigintType
	 *     BigintType returns BigintType
	 *
	 * Constraint:
	 *     {BigintType}
	 */
	protected void sequence_BigintType(ISerializationContext context, BigintType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns BlobType
	 *     BlobType returns BlobType
	 *
	 * Constraint:
	 *     {BlobType}
	 */
	protected void sequence_BlobType(ISerializationContext context, BlobType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns BoolType
	 *     BoolType returns BoolType
	 *
	 * Constraint:
	 *     {BoolType}
	 */
	protected void sequence_BoolType(ISerializationContext context, BoolType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns ChangeCustomDataTypeAttribute
	 *     ChangeCustomDataTypeAttribute returns ChangeCustomDataTypeAttribute
	 *
	 * Constraint:
	 *     (attributeToChange=[Attribute|EString] newType=[CustomDataType|EString])
	 */
	protected void sequence_ChangeCustomDataTypeAttribute(ISerializationContext context, ChangeCustomDataTypeAttribute semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.CHANGE_ATTRIBUTE_TYPE__ATTRIBUTE_TO_CHANGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.CHANGE_ATTRIBUTE_TYPE__ATTRIBUTE_TO_CHANGE));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.CHANGE_CUSTOM_DATA_TYPE_ATTRIBUTE__NEW_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.CHANGE_CUSTOM_DATA_TYPE_ATTRIBUTE__NEW_TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getChangeCustomDataTypeAttributeAccess().getAttributeToChangeAttributeEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.CHANGE_ATTRIBUTE_TYPE__ATTRIBUTE_TO_CHANGE, false));
		feeder.accept(grammarAccess.getChangeCustomDataTypeAttributeAccess().getNewTypeCustomDataTypeEStringParserRuleCall_5_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.CHANGE_CUSTOM_DATA_TYPE_ATTRIBUTE__NEW_TYPE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns ChangePrimitiveDataTypeAttribute
	 *     ChangePrimitiveDataTypeAttribute returns ChangePrimitiveDataTypeAttribute
	 *
	 * Constraint:
	 *     (maxSize=EInt? attributeToChange=[Attribute|EString])
	 */
	protected void sequence_ChangePrimitiveDataTypeAttribute(ISerializationContext context, ChangePrimitiveDataTypeAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns ChangeRelationCardinality
	 *     ChangeRelationCardinality returns ChangeRelationCardinality
	 *
	 * Constraint:
	 *     (relation=[Relation|EString] newCardinality=Cardinality)
	 */
	protected void sequence_ChangeRelationCardinality(ISerializationContext context, ChangeRelationCardinality semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.CHANGE_RELATION_CARDINALITY__RELATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.CHANGE_RELATION_CARDINALITY__RELATION));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.CHANGE_RELATION_CARDINALITY__NEW_CARDINALITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.CHANGE_RELATION_CARDINALITY__NEW_CARDINALITY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getChangeRelationCardinalityAccess().getRelationRelationEStringParserRuleCall_2_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.CHANGE_RELATION_CARDINALITY__RELATION, false));
		feeder.accept(grammarAccess.getChangeRelationCardinalityAccess().getNewCardinalityCardinalityEnumRuleCall_4_0(), semanticObject.getNewCardinality());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns ChangeRelationContainement
	 *     ChangeRelationContainement returns ChangeRelationContainement
	 *
	 * Constraint:
	 *     (relation=[Relation|EString] newContainment=EBooleanObject)
	 */
	protected void sequence_ChangeRelationContainement(ISerializationContext context, ChangeRelationContainement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.CHANGE_RELATION_CONTAINEMENT__RELATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.CHANGE_RELATION_CONTAINEMENT__RELATION));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.CHANGE_RELATION_CONTAINEMENT__NEW_CONTAINMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.CHANGE_RELATION_CONTAINEMENT__NEW_CONTAINMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getChangeRelationContainementAccess().getRelationRelationEStringParserRuleCall_2_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.CHANGE_RELATION_CONTAINEMENT__RELATION, false));
		feeder.accept(grammarAccess.getChangeRelationContainementAccess().getNewContainmentEBooleanObjectParserRuleCall_4_0(), semanticObject.getNewContainment());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Collection returns Collection
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString entity=[Entity|EString])
	 */
	protected void sequence_Collection(ISerializationContext context, Collection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Database returns ColumnDB
	 *     ColumnDB returns ColumnDB
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString (columns+=Column columns+=Column*)?)
	 */
	protected void sequence_ColumnDB(ISerializationContext context, ColumnDB semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Column returns Column
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString entity=[Entity|EString] (attributes+=[Attribute|EString] attributes+=[Attribute|EString]*)?)
	 */
	protected void sequence_Column(ISerializationContext context, Column semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EntityAttribute returns CustomAttribute
	 *     CustomAttribute returns CustomAttribute
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString type=[CustomDataType|EString])
	 */
	protected void sequence_CustomAttribute(ISerializationContext context, CustomAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     CustomDataTypeImplementationPackage returns CustomDataTypeImplementationPackage
	 *
	 * Constraint:
	 *     location=EString
	 */
	protected void sequence_CustomDataTypeImplementationPackage(ISerializationContext context, CustomDataTypeImplementationPackage semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.CUSTOM_DATA_TYPE_IMPLEMENTATION_PACKAGE__LOCATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.CUSTOM_DATA_TYPE_IMPLEMENTATION_PACKAGE__LOCATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCustomDataTypeImplementationPackageAccess().getLocationEStringParserRuleCall_1_0(), semanticObject.getLocation());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     CustomDataTypeItem returns CustomDataTypeItem
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString type=[DataType|EString] implementation=CustomDataTypeImplementationPackage)
	 */
	protected void sequence_CustomDataTypeItem(ISerializationContext context, CustomDataTypeItem semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns CustomDataType
	 *     CustomDataType returns CustomDataType
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString (elements+=CustomDataTypeItem elements+=CustomDataTypeItem*)?)
	 */
	protected void sequence_CustomDataType(ISerializationContext context, CustomDataType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns DateType
	 *     DateType returns DateType
	 *
	 * Constraint:
	 *     {DateType}
	 */
	protected void sequence_DateType(ISerializationContext context, DateType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns DatetimeType
	 *     DatetimeType returns DatetimeType
	 *
	 * Constraint:
	 *     {DatetimeType}
	 */
	protected void sequence_DatetimeType(ISerializationContext context, DatetimeType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns DisableBidirectionalRelation
	 *     DisableBidirectionalRelation returns DisableBidirectionalRelation
	 *
	 * Constraint:
	 *     relation=[Relation|EString]
	 */
	protected void sequence_DisableBidirectionalRelation(ISerializationContext context, DisableBidirectionalRelation semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.DISABLE_BIDIRECTIONAL_RELATION__RELATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.DISABLE_BIDIRECTIONAL_RELATION__RELATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDisableBidirectionalRelationAccess().getRelationRelationEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.DISABLE_BIDIRECTIONAL_RELATION__RELATION, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns DisableRelationContainment
	 *     DisableRelationContainment returns DisableRelationContainment
	 *
	 * Constraint:
	 *     relation=[Relation|EString]
	 */
	protected void sequence_DisableRelationContainment(ISerializationContext context, DisableRelationContainment semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.DISABLE_RELATION_CONTAINMENT__RELATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.DISABLE_RELATION_CONTAINMENT__RELATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDisableRelationContainmentAccess().getRelationRelationEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.DISABLE_RELATION_CONTAINMENT__RELATION, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Database returns DocumentDB
	 *     DocumentDB returns DocumentDB
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString (collections+=Collection collections+=Collection*)?)
	 */
	protected void sequence_DocumentDB(ISerializationContext context, DocumentDB semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns DropCollectionIndex
	 *     DropCollectionIndex returns DropCollectionIndex
	 *
	 * Constraint:
	 *     collection=[Collection|EString]
	 */
	protected void sequence_DropCollectionIndex(ISerializationContext context, DropCollectionIndex semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.DROP_COLLECTION_INDEX__COLLECTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.DROP_COLLECTION_INDEX__COLLECTION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDropCollectionIndexAccess().getCollectionCollectionEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.DROP_COLLECTION_INDEX__COLLECTION, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     DropIndexTable returns DropIndex
	 *
	 * Constraint:
	 *     table=[Table|EString]
	 */
	protected void sequence_DropIndexTable(ISerializationContext context, DropIndex semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.DROP_INDEX__TABLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.DROP_INDEX__TABLE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDropIndexTableAccess().getTableTableEStringParserRuleCall_2_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.DROP_INDEX__TABLE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns DropIndex
	 *     DropIndex returns DropIndex
	 *
	 * Constraint:
	 *     table=[Table|EString]
	 */
	protected void sequence_DropIndex(ISerializationContext context, DropIndex semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.DROP_INDEX__TABLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.DROP_INDEX__TABLE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDropIndexAccess().getTableTableEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.DROP_INDEX__TABLE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns EnableBidirectionalRelation
	 *     EnableBidirectionalRelation returns EnableBidirectionalRelation
	 *
	 * Constraint:
	 *     relation=[Relation|EString]
	 */
	protected void sequence_EnableBidirectionalRelation(ISerializationContext context, EnableBidirectionalRelation semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.ENABLE_BIDIRECTIONAL_RELATION__RELATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.ENABLE_BIDIRECTIONAL_RELATION__RELATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEnableBidirectionalRelationAccess().getRelationRelationEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.ENABLE_BIDIRECTIONAL_RELATION__RELATION, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns EnableRelationContainment
	 *     EnableRelationContainment returns EnableRelationContainment
	 *
	 * Constraint:
	 *     relation=[Relation|EString]
	 */
	protected void sequence_EnableRelationContainment(ISerializationContext context, EnableRelationContainment semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.ENABLE_RELATION_CONTAINMENT__RELATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.ENABLE_RELATION_CONTAINMENT__RELATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEnableRelationContainmentAccess().getRelationRelationEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.ENABLE_RELATION_CONTAINMENT__RELATION, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Entity returns Entity
	 *     Entity_Impl returns Entity
	 *
	 * Constraint:
	 *     (
	 *         (functionalTags+=FunctionalTag_Impl functionalTags+=FunctionalTag_Impl*)? 
	 *         (nfunctionalTags+=NFunctionalTag_Impl nfunctionalTags+=NFunctionalTag_Impl*)? 
	 *         importedNamespace=EString? 
	 *         name=EString 
	 *         (attributes+=EntityAttribute attributes+=EntityAttribute*)? 
	 *         (relations+=Relation relations+=Relation*)?
	 *     )
	 */
	protected void sequence_Entity_Impl(ISerializationContext context, Entity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns FloatType
	 *     FloatType returns FloatType
	 *
	 * Constraint:
	 *     {FloatType}
	 */
	protected void sequence_FloatType(ISerializationContext context, FloatType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns FreetextType
	 *     FreetextType returns FreetextType
	 *
	 * Constraint:
	 *     (workflowName=EString tasks=NlpTask)
	 */
	protected void sequence_FreetextType(ISerializationContext context, FreetextType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.FREETEXT_TYPE__WORKFLOW_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.FREETEXT_TYPE__WORKFLOW_NAME));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.FREETEXT_TYPE__TASKS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.FREETEXT_TYPE__TASKS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFreetextTypeAccess().getWorkflowNameEStringParserRuleCall_2_0(), semanticObject.getWorkflowName());
		feeder.accept(grammarAccess.getFreetextTypeAccess().getTasksNlpTaskParserRuleCall_4_0(), semanticObject.getTasks());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     FunctionalTag_Impl returns FunctionalTag
	 *
	 * Constraint:
	 *     name=EString
	 */
	protected void sequence_FunctionalTag_Impl(ISerializationContext context, FunctionalTag semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.NAMED_ELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFunctionalTag_ImplAccess().getNameEStringParserRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     GraphAttribute returns GraphAttribute
	 *     GraphAttribute_Impl returns GraphAttribute
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString value=[Attribute|EString]?)
	 */
	protected void sequence_GraphAttribute_Impl(ISerializationContext context, GraphAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Database returns GraphDB
	 *     GraphDB returns GraphDB
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString (nodes+=GraphNode nodes+=GraphNode*)? (edges+=GraphEdge edges+=GraphEdge*)?)
	 */
	protected void sequence_GraphDB(ISerializationContext context, GraphDB semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GraphEdgeLabel returns GraphEdgeLabel
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString type=[DataType|EString])
	 */
	protected void sequence_GraphEdgeLabel(ISerializationContext context, GraphEdgeLabel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GraphEdge returns GraphEdge
	 *     GraphEdge_Impl returns GraphEdge
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString from=[GraphNode|EString]? to=[GraphNode|EString]? (labels+=GraphEdgeLabel labels+=GraphEdgeLabel*)?)
	 */
	protected void sequence_GraphEdge_Impl(ISerializationContext context, GraphEdge semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GraphNode returns GraphNode
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString entity=[Entity|EString] (attributes+=GraphAttribute attributes+=GraphAttribute*)?)
	 */
	protected void sequence_GraphNode(ISerializationContext context, GraphNode semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     IdSpec returns IdSpec
	 *
	 * Constraint:
	 *     (attributes+=[Attribute|EString] attributes+=[Attribute|EString]*)?
	 */
	protected void sequence_IdSpec(ISerializationContext context, IdSpec semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     IndexSpec returns IndexSpec
	 *
	 * Constraint:
	 *     (
	 *         importedNamespace=EString? 
	 *         name=EString 
	 *         (attributes+=[Attribute|EString] attributes+=[Attribute|EString]*)? 
	 *         (references+=[Relation|EString] references+=[Relation|EString]*)?
	 *     )
	 */
	protected void sequence_IndexSpec(ISerializationContext context, IndexSpec semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns IntType
	 *     IntType returns IntType
	 *
	 * Constraint:
	 *     {IntType}
	 */
	protected void sequence_IntType(ISerializationContext context, IntType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Database returns KeyValueDB
	 *     KeyValueDB returns KeyValueDB
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString (elements+=KeyValueElement elements+=KeyValueElement*)?)
	 */
	protected void sequence_KeyValueDB(ISerializationContext context, KeyValueDB semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     KeyValueElement returns KeyValueElement
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString key=EString (values+=[Attribute|EString] values+=[Attribute|EString]*)?)
	 */
	protected void sequence_KeyValueElement(ISerializationContext context, KeyValueElement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns MergeEntity
	 *     MergeEntity returns MergeEntity
	 *
	 * Constraint:
	 *     (firstEntityToMerge=[Entity|EString] secondEntityToMerge=[Entity|EString] newEntityName=EString)
	 */
	protected void sequence_MergeEntity(ISerializationContext context, MergeEntity semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.MERGE_ENTITY__FIRST_ENTITY_TO_MERGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.MERGE_ENTITY__FIRST_ENTITY_TO_MERGE));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.MERGE_ENTITY__SECOND_ENTITY_TO_MERGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.MERGE_ENTITY__SECOND_ENTITY_TO_MERGE));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.MERGE_ENTITY__NEW_ENTITY_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.MERGE_ENTITY__NEW_ENTITY_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMergeEntityAccess().getFirstEntityToMergeEntityEStringParserRuleCall_2_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.MERGE_ENTITY__FIRST_ENTITY_TO_MERGE, false));
		feeder.accept(grammarAccess.getMergeEntityAccess().getSecondEntityToMergeEntityEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.MERGE_ENTITY__SECOND_ENTITY_TO_MERGE, false));
		feeder.accept(grammarAccess.getMergeEntityAccess().getNewEntityNameEStringParserRuleCall_5_0(), semanticObject.getNewEntityName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns MigrateEntity
	 *     MigrateEntity returns MigrateEntity
	 *
	 * Constraint:
	 *     (entity=[Entity|EString] newDatabase=[Database|EString])
	 */
	protected void sequence_MigrateEntity(ISerializationContext context, MigrateEntity semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.MIGRATE_ENTITY__ENTITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.MIGRATE_ENTITY__ENTITY));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.MIGRATE_ENTITY__NEW_DATABASE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.MIGRATE_ENTITY__NEW_DATABASE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMigrateEntityAccess().getEntityEntityEStringParserRuleCall_1_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.MIGRATE_ENTITY__ENTITY, false));
		feeder.accept(grammarAccess.getMigrateEntityAccess().getNewDatabaseDatabaseEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.MIGRATE_ENTITY__NEW_DATABASE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (entities+=Entity* customDataTypes+=CustomDataType* databases+=Database* (changeOperators+=ChangeOperator changeOperators+=ChangeOperator*)?)
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     NFunctionalTag_Impl returns NFunctionalTag
	 *
	 * Constraint:
	 *     name=EString
	 */
	protected void sequence_NFunctionalTag_Impl(ISerializationContext context, NFunctionalTag semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.NAMED_ELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNFunctionalTag_ImplAccess().getNameEStringParserRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     NlpTask returns NlpTask
	 *
	 * Constraint:
	 *     (type=NlpTaskType parameters+=EString?)
	 */
	protected void sequence_NlpTask(ISerializationContext context, NlpTask semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns PointType
	 *     PointType returns PointType
	 *
	 * Constraint:
	 *     {PointType}
	 */
	protected void sequence_PointType(ISerializationContext context, PointType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns PolygonType
	 *     PolygonType returns PolygonType
	 *
	 * Constraint:
	 *     {PolygonType}
	 */
	protected void sequence_PolygonType(ISerializationContext context, PolygonType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Relation returns Relation
	 *     Relation_Impl returns Relation
	 *
	 * Constraint:
	 *     (
	 *         importedNamespace=EString? 
	 *         name=EString 
	 *         isContainment?=':'? 
	 *         type=[Entity|EString] 
	 *         opposite=[Relation|EString]? 
	 *         cardinality=Cardinality?
	 *     )
	 */
	protected void sequence_Relation_Impl(ISerializationContext context, Relation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Database returns RelationalDB
	 *     RelationalDB returns RelationalDB
	 *
	 * Constraint:
	 *     (importedNamespace=EString? name=EString (tables+=Table tables+=Table*)?)
	 */
	protected void sequence_RelationalDB(ISerializationContext context, RelationalDB semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns RemoveAttribute
	 *     RemoveAttribute returns RemoveAttribute
	 *
	 * Constraint:
	 *     attributeToRemove=[Attribute|EString]
	 */
	protected void sequence_RemoveAttribute(ISerializationContext context, RemoveAttribute semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.REMOVE_ATTRIBUTE__ATTRIBUTE_TO_REMOVE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.REMOVE_ATTRIBUTE__ATTRIBUTE_TO_REMOVE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRemoveAttributeAccess().getAttributeToRemoveAttributeEStringParserRuleCall_2_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.REMOVE_ATTRIBUTE__ATTRIBUTE_TO_REMOVE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns RemoveAttributesToIndex
	 *     RemoveAttributesToIndex returns RemoveAttributesToIndex
	 *
	 * Constraint:
	 *     (table=[Table|EString] attributes+=[Attribute|EString] attributes+=[Attribute|EString]?)
	 */
	protected void sequence_RemoveAttributesToIndex(ISerializationContext context, RemoveAttributesToIndex semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns RemoveEntity
	 *     RemoveEntity returns RemoveEntity
	 *
	 * Constraint:
	 *     entityToRemove=[Entity|EString]
	 */
	protected void sequence_RemoveEntity(ISerializationContext context, RemoveEntity semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.REMOVE_ENTITY__ENTITY_TO_REMOVE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.REMOVE_ENTITY__ENTITY_TO_REMOVE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRemoveEntityAccess().getEntityToRemoveEntityEStringParserRuleCall_2_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.REMOVE_ENTITY__ENTITY_TO_REMOVE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns RemoveGraphAttribute
	 *     RemoveGraphAttribute returns RemoveGraphAttribute
	 *
	 * Constraint:
	 *     node=[GraphNode|EString]
	 */
	protected void sequence_RemoveGraphAttribute(ISerializationContext context, RemoveGraphAttribute semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.REMOVE_GRAPH_ATTRIBUTE__NODE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.REMOVE_GRAPH_ATTRIBUTE__NODE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRemoveGraphAttributeAccess().getNodeGraphNodeEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.REMOVE_GRAPH_ATTRIBUTE__NODE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns RemoveGraphEdge
	 *     RemoveGraphEdge returns RemoveGraphEdge
	 *
	 * Constraint:
	 *     graphEdgeToRemove=[GraphEdge|EString]
	 */
	protected void sequence_RemoveGraphEdge(ISerializationContext context, RemoveGraphEdge semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.REMOVE_GRAPH_EDGE__GRAPH_EDGE_TO_REMOVE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.REMOVE_GRAPH_EDGE__GRAPH_EDGE_TO_REMOVE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRemoveGraphEdgeAccess().getGraphEdgeToRemoveGraphEdgeEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.REMOVE_GRAPH_EDGE__GRAPH_EDGE_TO_REMOVE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns RemoveRelation
	 *     RemoveRelation returns RemoveRelation
	 *
	 * Constraint:
	 *     relationToRemove=[Relation|EString]
	 */
	protected void sequence_RemoveRelation(ISerializationContext context, RemoveRelation semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.REMOVE_RELATION__RELATION_TO_REMOVE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.REMOVE_RELATION__RELATION_TO_REMOVE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRemoveRelationAccess().getRelationToRemoveRelationEStringParserRuleCall_2_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.REMOVE_RELATION__RELATION_TO_REMOVE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns RenabeGraphEdgeLabel
	 *     RenabeGraphEdgeLabel returns RenabeGraphEdgeLabel
	 *
	 * Constraint:
	 *     (newName=EString? edge=[GraphEdge|EString])
	 */
	protected void sequence_RenabeGraphEdgeLabel(ISerializationContext context, RenabeGraphEdgeLabel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns RenameAttribute
	 *     RenameAttribute returns RenameAttribute
	 *
	 * Constraint:
	 *     (attributeToRename=[Attribute|EString] newName=EString)
	 */
	protected void sequence_RenameAttribute(ISerializationContext context, RenameAttribute semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.RENAME_ATTRIBUTE__ATTRIBUTE_TO_RENAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.RENAME_ATTRIBUTE__ATTRIBUTE_TO_RENAME));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.RENAME_ATTRIBUTE__NEW_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.RENAME_ATTRIBUTE__NEW_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRenameAttributeAccess().getAttributeToRenameAttributeEStringParserRuleCall_2_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.RENAME_ATTRIBUTE__ATTRIBUTE_TO_RENAME, false));
		feeder.accept(grammarAccess.getRenameAttributeAccess().getNewNameEStringParserRuleCall_4_0(), semanticObject.getNewName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns RenameCollection
	 *     RenameCollection returns RenameCollection
	 *
	 * Constraint:
	 *     (collectionToRename=[Collection|EString] newName=EString)
	 */
	protected void sequence_RenameCollection(ISerializationContext context, RenameCollection semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.RENAME_COLLECTION__COLLECTION_TO_RENAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.RENAME_COLLECTION__COLLECTION_TO_RENAME));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.RENAME_COLLECTION__NEW_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.RENAME_COLLECTION__NEW_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRenameCollectionAccess().getCollectionToRenameCollectionEStringParserRuleCall_2_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.RENAME_COLLECTION__COLLECTION_TO_RENAME, false));
		feeder.accept(grammarAccess.getRenameCollectionAccess().getNewNameEStringParserRuleCall_4_0(), semanticObject.getNewName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns RenameEntity
	 *     RenameEntity returns RenameEntity
	 *
	 * Constraint:
	 *     (entityToRename=[Entity|EString] newEntityName=EString)
	 */
	protected void sequence_RenameEntity(ISerializationContext context, RenameEntity semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.RENAME_ENTITY__ENTITY_TO_RENAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.RENAME_ENTITY__ENTITY_TO_RENAME));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.RENAME_ENTITY__NEW_ENTITY_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.RENAME_ENTITY__NEW_ENTITY_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRenameEntityAccess().getEntityToRenameEntityEStringParserRuleCall_2_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.RENAME_ENTITY__ENTITY_TO_RENAME, false));
		feeder.accept(grammarAccess.getRenameEntityAccess().getNewEntityNameEStringParserRuleCall_4_0(), semanticObject.getNewEntityName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns RenameRelation
	 *     RenameRelation returns RenameRelation
	 *
	 * Constraint:
	 *     (relationToRename=[Relation|EString] newRelationName=EString)
	 */
	protected void sequence_RenameRelation(ISerializationContext context, RenameRelation semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.RENAME_RELATION__RELATION_TO_RENAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.RENAME_RELATION__RELATION_TO_RENAME));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.RENAME_RELATION__NEW_RELATION_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.RENAME_RELATION__NEW_RELATION_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRenameRelationAccess().getRelationToRenameRelationEStringParserRuleCall_2_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.RENAME_RELATION__RELATION_TO_RENAME, false));
		feeder.accept(grammarAccess.getRenameRelationAccess().getNewRelationNameEStringParserRuleCall_4_0(), semanticObject.getNewRelationName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns RenameTable
	 *     RenameTable returns RenameTable
	 *
	 * Constraint:
	 *     (tableToRename=[Table|EString] newName=EString)
	 */
	protected void sequence_RenameTable(ISerializationContext context, RenameTable semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.RENAME_TABLE__TABLE_TO_RENAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.RENAME_TABLE__TABLE_TO_RENAME));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.RENAME_TABLE__NEW_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.RENAME_TABLE__NEW_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRenameTableAccess().getTableToRenameTableEStringParserRuleCall_2_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.RENAME_TABLE__TABLE_TO_RENAME, false));
		feeder.accept(grammarAccess.getRenameTableAccess().getNewNameEStringParserRuleCall_4_0(), semanticObject.getNewName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns SplitEntityHorizontal
	 *     SplitEntityHorizontal returns SplitEntityHorizontal
	 *
	 * Constraint:
	 *     (entity1=[Entity|EString] entity2name=EString attribute=[Attribute|EString] expression=STRING)
	 */
	protected void sequence_SplitEntityHorizontal(ISerializationContext context, SplitEntityHorizontal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY_HORIZONTAL__ENTITY1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY_HORIZONTAL__ENTITY1));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY_HORIZONTAL__ENTITY2NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY_HORIZONTAL__ENTITY2NAME));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY_HORIZONTAL__ATTRIBUTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY_HORIZONTAL__ATTRIBUTE));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY_HORIZONTAL__EXPRESSION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY_HORIZONTAL__EXPRESSION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSplitEntityHorizontalAccess().getEntity1EntityEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.SPLIT_ENTITY_HORIZONTAL__ENTITY1, false));
		feeder.accept(grammarAccess.getSplitEntityHorizontalAccess().getEntity2nameEStringParserRuleCall_5_0(), semanticObject.getEntity2name());
		feeder.accept(grammarAccess.getSplitEntityHorizontalAccess().getAttributeAttributeEStringParserRuleCall_7_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.SPLIT_ENTITY_HORIZONTAL__ATTRIBUTE, false));
		feeder.accept(grammarAccess.getSplitEntityHorizontalAccess().getExpressionSTRINGTerminalRuleCall_9_0(), semanticObject.getExpression());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns SplitEntityVertical
	 *     SplitEntityVertical returns SplitEntityVertical
	 *
	 * Constraint:
	 *     (entity1=[Entity|EString] entity2name=EString (attributeList+=[Attribute|EString] attributeList+=[Attribute|EString]*)*)
	 */
	protected void sequence_SplitEntityVertical(ISerializationContext context, SplitEntityVertical semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ChangeOperator returns SplitEntity
	 *     SplitEntity returns SplitEntity
	 *
	 * Constraint:
	 *     (entityToBeSplit=[Entity|EString] firstNewEntity=Entity secondNewEntity=Entity)
	 */
	protected void sequence_SplitEntity(ISerializationContext context, SplitEntity semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY__ENTITY_TO_BE_SPLIT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY__ENTITY_TO_BE_SPLIT));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY__FIRST_NEW_ENTITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY__FIRST_NEW_ENTITY));
			if (transientValues.isValueTransient(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY__SECOND_NEW_ENTITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TyphonmlPackage.Literals.SPLIT_ENTITY__SECOND_NEW_ENTITY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSplitEntityAccess().getEntityToBeSplitEntityEStringParserRuleCall_3_0_1(), semanticObject.eGet(TyphonmlPackage.Literals.SPLIT_ENTITY__ENTITY_TO_BE_SPLIT, false));
		feeder.accept(grammarAccess.getSplitEntityAccess().getFirstNewEntityEntityParserRuleCall_5_0(), semanticObject.getFirstNewEntity());
		feeder.accept(grammarAccess.getSplitEntityAccess().getSecondNewEntityEntityParserRuleCall_7_0(), semanticObject.getSecondNewEntity());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns StringType
	 *     StringType returns StringType
	 *
	 * Constraint:
	 *     maxSize=EInt?
	 */
	protected void sequence_StringType(ISerializationContext context, StringType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Table returns Table
	 *
	 * Constraint:
	 *     (
	 *         importedNamespace=EString? 
	 *         name=EString 
	 *         entity=[Entity|EString]? 
	 *         db=[Database|EString]? 
	 *         indexSpec=IndexSpec? 
	 *         idSpec=IdSpec?
	 *     )
	 */
	protected void sequence_Table(ISerializationContext context, Table semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns TextType
	 *     TextType returns TextType
	 *
	 * Constraint:
	 *     {TextType}
	 */
	protected void sequence_TextType(ISerializationContext context, TextType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
