/*
 * generated by Xtext 2.14.0
 */
package org.typhon.dsls.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTyphonMLScopeProvider extends DelegatingScopeProvider {
}
