/**
 * generated by Xtext 2.12.0
 */
package org.typhon.dsls.xtext;

import org.typhon.dsls.xtext.TyphonMLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TyphonMLStandaloneSetup extends TyphonMLStandaloneSetupGenerated {
  public static void doSetup() {
    new TyphonMLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
