/**
 * generated by Xtext 2.12.0
 */
package org.typhon.dsls.xtext;

import org.typhon.dsls.xtext.AbstractTyphonMLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TyphonMLRuntimeModule extends AbstractTyphonMLRuntimeModule {
}
