/*
 * generated by Xtext 2.15.0
 */
package it.univaq.disim.typhon.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTyphonMLScopeProvider extends DelegatingScopeProvider {
}
