/*
 * generated by Xtext 2.19.0
 */
package it.univaq.disim.typhon.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import it.univaq.disim.typhon.ide.contentassist.antlr.internal.InternalTyphonMLParser;
import it.univaq.disim.typhon.services.TyphonMLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class TyphonMLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TyphonMLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TyphonMLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
			builder.put(grammarAccess.getEBooleanObjectAccess().getAlternatives(), "rule__EBooleanObject__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getSuperDataTypeAccess().getAlternatives(), "rule__SuperDataType__Alternatives");
			builder.put(grammarAccess.getAttributeAccess().getAlternatives(), "rule__Attribute__Alternatives");
			builder.put(grammarAccess.getEntityAttributeKindAccess().getAlternatives(), "rule__EntityAttributeKind__Alternatives");
			builder.put(grammarAccess.getDatabaseAccess().getAlternatives(), "rule__Database__Alternatives");
			builder.put(grammarAccess.getGraphAttributeAccess().getAlternatives(), "rule__GraphAttribute__Alternatives");
			builder.put(grammarAccess.getGraphEdgeAccess().getAlternatives(), "rule__GraphEdge__Alternatives");
			builder.put(grammarAccess.getChangeOperatorAccess().getAlternatives(), "rule__ChangeOperator__Alternatives");
			builder.put(grammarAccess.getCardinalityAccess().getAlternatives(), "rule__Cardinality__Alternatives");
			builder.put(grammarAccess.getNlpTaskTypeAccess().getAlternatives(), "rule__NlpTaskType__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup_4(), "rule__Model__Group_4__0");
			builder.put(grammarAccess.getModelAccess().getGroup_4_3(), "rule__Model__Group_4_3__0");
			builder.put(grammarAccess.getIntTypeAccess().getGroup(), "rule__IntType__Group__0");
			builder.put(grammarAccess.getBigintTypeAccess().getGroup(), "rule__BigintType__Group__0");
			builder.put(grammarAccess.getStringTypeAccess().getGroup(), "rule__StringType__Group__0");
			builder.put(grammarAccess.getStringTypeAccess().getGroup_2(), "rule__StringType__Group_2__0");
			builder.put(grammarAccess.getTextTypeAccess().getGroup(), "rule__TextType__Group__0");
			builder.put(grammarAccess.getPointTypeAccess().getGroup(), "rule__PointType__Group__0");
			builder.put(grammarAccess.getPolygonTypeAccess().getGroup(), "rule__PolygonType__Group__0");
			builder.put(grammarAccess.getBoolTypeAccess().getGroup(), "rule__BoolType__Group__0");
			builder.put(grammarAccess.getFloatTypeAccess().getGroup(), "rule__FloatType__Group__0");
			builder.put(grammarAccess.getBlobTypeAccess().getGroup(), "rule__BlobType__Group__0");
			builder.put(grammarAccess.getFreetextTypeAccess().getGroup(), "rule__FreetextType__Group__0");
			builder.put(grammarAccess.getFreetextTypeAccess().getGroup_2(), "rule__FreetextType__Group_2__0");
			builder.put(grammarAccess.getFreetextTypeAccess().getGroup_2_2(), "rule__FreetextType__Group_2_2__0");
			builder.put(grammarAccess.getDateTypeAccess().getGroup(), "rule__DateType__Group__0");
			builder.put(grammarAccess.getDatetimeTypeAccess().getGroup(), "rule__DatetimeType__Group__0");
			builder.put(grammarAccess.getNlpTaskAccess().getGroup(), "rule__NlpTask__Group__0");
			builder.put(grammarAccess.getCustomDataTypeAccess().getGroup(), "rule__CustomDataType__Group__0");
			builder.put(grammarAccess.getCustomDataTypeAccess().getGroup_4(), "rule__CustomDataType__Group_4__0");
			builder.put(grammarAccess.getCustomDataTypeAccess().getGroup_5(), "rule__CustomDataType__Group_5__0");
			builder.put(grammarAccess.getCustomDataTypeAccess().getGroup_5_1(), "rule__CustomDataType__Group_5_1__0");
			builder.put(grammarAccess.getComplexDataTypeAccess().getGroup(), "rule__ComplexDataType__Group__0");
			builder.put(grammarAccess.getComplexDataTypeAccess().getGroup_0(), "rule__ComplexDataType__Group_0__0");
			builder.put(grammarAccess.getSimpleDataTypeAccess().getGroup(), "rule__SimpleDataType__Group__0");
			builder.put(grammarAccess.getCustomDataTypeImplementationPackageAccess().getGroup(), "rule__CustomDataTypeImplementationPackage__Group__0");
			builder.put(grammarAccess.getEntity_ImplAccess().getGroup(), "rule__Entity_Impl__Group__0");
			builder.put(grammarAccess.getEntity_ImplAccess().getGroup_0(), "rule__Entity_Impl__Group_0__0");
			builder.put(grammarAccess.getEntity_ImplAccess().getGroup_0_2(), "rule__Entity_Impl__Group_0_2__0");
			builder.put(grammarAccess.getEntity_ImplAccess().getGroup_0_2_1(), "rule__Entity_Impl__Group_0_2_1__0");
			builder.put(grammarAccess.getEntity_ImplAccess().getGroup_1(), "rule__Entity_Impl__Group_1__0");
			builder.put(grammarAccess.getEntity_ImplAccess().getGroup_1_2(), "rule__Entity_Impl__Group_1_2__0");
			builder.put(grammarAccess.getEntity_ImplAccess().getGroup_1_2_1(), "rule__Entity_Impl__Group_1_2_1__0");
			builder.put(grammarAccess.getEntity_ImplAccess().getGroup_2(), "rule__Entity_Impl__Group_2__0");
			builder.put(grammarAccess.getEntity_ImplAccess().getGroup_6(), "rule__Entity_Impl__Group_6__0");
			builder.put(grammarAccess.getEntity_ImplAccess().getGroup_7(), "rule__Entity_Impl__Group_7__0");
			builder.put(grammarAccess.getAttribute_ImplAccess().getGroup(), "rule__Attribute_Impl__Group__0");
			builder.put(grammarAccess.getAttribute_ImplAccess().getGroup_1(), "rule__Attribute_Impl__Group_1__0");
			builder.put(grammarAccess.getCustomAttributeAccess().getGroup(), "rule__CustomAttribute__Group__0");
			builder.put(grammarAccess.getCustomAttributeAccess().getGroup_1(), "rule__CustomAttribute__Group_1__0");
			builder.put(grammarAccess.getRelation_ImplAccess().getGroup(), "rule__Relation_Impl__Group__0");
			builder.put(grammarAccess.getRelation_ImplAccess().getGroup_0(), "rule__Relation_Impl__Group_0__0");
			builder.put(grammarAccess.getRelation_ImplAccess().getGroup_5(), "rule__Relation_Impl__Group_5__0");
			builder.put(grammarAccess.getRelation_ImplAccess().getGroup_6(), "rule__Relation_Impl__Group_6__0");
			builder.put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
			builder.put(grammarAccess.getTableAccess().getGroup_0(), "rule__Table__Group_0__0");
			builder.put(grammarAccess.getTableAccess().getGroup_6(), "rule__Table__Group_6__0");
			builder.put(grammarAccess.getCollectionAccess().getGroup(), "rule__Collection__Group__0");
			builder.put(grammarAccess.getCollectionAccess().getGroup_0(), "rule__Collection__Group_0__0");
			builder.put(grammarAccess.getKeyValueElementAccess().getGroup(), "rule__KeyValueElement__Group__0");
			builder.put(grammarAccess.getKeyValueElementAccess().getGroup_0(), "rule__KeyValueElement__Group_0__0");
			builder.put(grammarAccess.getKeyValueElementAccess().getGroup_6(), "rule__KeyValueElement__Group_6__0");
			builder.put(grammarAccess.getKeyValueElementAccess().getGroup_6_1(), "rule__KeyValueElement__Group_6_1__0");
			builder.put(grammarAccess.getGraphNodeAccess().getGroup(), "rule__GraphNode__Group__0");
			builder.put(grammarAccess.getGraphNodeAccess().getGroup_0(), "rule__GraphNode__Group_0__0");
			builder.put(grammarAccess.getGraphNodeAccess().getGroup_5(), "rule__GraphNode__Group_5__0");
			builder.put(grammarAccess.getGraphNodeAccess().getGroup_5_2(), "rule__GraphNode__Group_5_2__0");
			builder.put(grammarAccess.getColumnAccess().getGroup(), "rule__Column__Group__0");
			builder.put(grammarAccess.getColumnAccess().getGroup_0(), "rule__Column__Group_0__0");
			builder.put(grammarAccess.getColumnAccess().getGroup_6(), "rule__Column__Group_6__0");
			builder.put(grammarAccess.getColumnAccess().getGroup_6_3(), "rule__Column__Group_6_3__0");
			builder.put(grammarAccess.getIndexSpecAccess().getGroup(), "rule__IndexSpec__Group__0");
			builder.put(grammarAccess.getIndexSpecAccess().getGroup_1(), "rule__IndexSpec__Group_1__0");
			builder.put(grammarAccess.getIndexSpecAccess().getGroup_5(), "rule__IndexSpec__Group_5__0");
			builder.put(grammarAccess.getIndexSpecAccess().getGroup_5_3(), "rule__IndexSpec__Group_5_3__0");
			builder.put(grammarAccess.getIndexSpecAccess().getGroup_6(), "rule__IndexSpec__Group_6__0");
			builder.put(grammarAccess.getIndexSpecAccess().getGroup_6_3(), "rule__IndexSpec__Group_6_3__0");
			builder.put(grammarAccess.getIdSpecAccess().getGroup(), "rule__IdSpec__Group__0");
			builder.put(grammarAccess.getIdSpecAccess().getGroup_2(), "rule__IdSpec__Group_2__0");
			builder.put(grammarAccess.getIdSpecAccess().getGroup_2_2(), "rule__IdSpec__Group_2_2__0");
			builder.put(grammarAccess.getRelationalDBAccess().getGroup(), "rule__RelationalDB__Group__0");
			builder.put(grammarAccess.getRelationalDBAccess().getGroup_1(), "rule__RelationalDB__Group_1__0");
			builder.put(grammarAccess.getRelationalDBAccess().getGroup_5(), "rule__RelationalDB__Group_5__0");
			builder.put(grammarAccess.getDocumentDBAccess().getGroup(), "rule__DocumentDB__Group__0");
			builder.put(grammarAccess.getDocumentDBAccess().getGroup_1(), "rule__DocumentDB__Group_1__0");
			builder.put(grammarAccess.getDocumentDBAccess().getGroup_5(), "rule__DocumentDB__Group_5__0");
			builder.put(grammarAccess.getKeyValueDBAccess().getGroup(), "rule__KeyValueDB__Group__0");
			builder.put(grammarAccess.getKeyValueDBAccess().getGroup_1(), "rule__KeyValueDB__Group_1__0");
			builder.put(grammarAccess.getKeyValueDBAccess().getGroup_5(), "rule__KeyValueDB__Group_5__0");
			builder.put(grammarAccess.getKeyValueDBAccess().getGroup_5_3(), "rule__KeyValueDB__Group_5_3__0");
			builder.put(grammarAccess.getGraphDBAccess().getGroup(), "rule__GraphDB__Group__0");
			builder.put(grammarAccess.getGraphDBAccess().getGroup_1(), "rule__GraphDB__Group_1__0");
			builder.put(grammarAccess.getGraphDBAccess().getGroup_5(), "rule__GraphDB__Group_5__0");
			builder.put(grammarAccess.getGraphDBAccess().getGroup_5_3(), "rule__GraphDB__Group_5_3__0");
			builder.put(grammarAccess.getColumnDBAccess().getGroup(), "rule__ColumnDB__Group__0");
			builder.put(grammarAccess.getColumnDBAccess().getGroup_1(), "rule__ColumnDB__Group_1__0");
			builder.put(grammarAccess.getColumnDBAccess().getGroup_5(), "rule__ColumnDB__Group_5__0");
			builder.put(grammarAccess.getColumnDBAccess().getGroup_5_3(), "rule__ColumnDB__Group_5_3__0");
			builder.put(grammarAccess.getGraphEdge_ImplAccess().getGroup(), "rule__GraphEdge_Impl__Group__0");
			builder.put(grammarAccess.getGraphEdge_ImplAccess().getGroup_4(), "rule__GraphEdge_Impl__Group_4__0");
			builder.put(grammarAccess.getGraphEdge_ImplAccess().getGroup_5(), "rule__GraphEdge_Impl__Group_5__0");
			builder.put(grammarAccess.getGraphEdgeLabelAccess().getGroup(), "rule__GraphEdgeLabel__Group__0");
			builder.put(grammarAccess.getGraphEdgeLabelAccess().getGroup_1(), "rule__GraphEdgeLabel__Group_1__0");
			builder.put(grammarAccess.getGraphAttribute_ImplAccess().getGroup(), "rule__GraphAttribute_Impl__Group__0");
			builder.put(grammarAccess.getGraphAttribute_ImplAccess().getGroup_1(), "rule__GraphAttribute_Impl__Group_1__0");
			builder.put(grammarAccess.getAddCustomDataTypeAttributeAccess().getGroup(), "rule__AddCustomDataTypeAttribute__Group__0");
			builder.put(grammarAccess.getAddCustomDataTypeAttributeAccess().getGroup_3(), "rule__AddCustomDataTypeAttribute__Group_3__0");
			builder.put(grammarAccess.getChangePrimitiveDataTypeAttributeAccess().getGroup(), "rule__ChangePrimitiveDataTypeAttribute__Group__0");
			builder.put(grammarAccess.getChangePrimitiveDataTypeAttributeAccess().getGroup_2(), "rule__ChangePrimitiveDataTypeAttribute__Group_2__0");
			builder.put(grammarAccess.getChangeCustomDataTypeAttributeAccess().getGroup(), "rule__ChangeCustomDataTypeAttribute__Group__0");
			builder.put(grammarAccess.getAddEntityAccess().getGroup(), "rule__AddEntity__Group__0");
			builder.put(grammarAccess.getAddEntityAccess().getGroup_0(), "rule__AddEntity__Group_0__0");
			builder.put(grammarAccess.getAddEntityAccess().getGroup_5(), "rule__AddEntity__Group_5__0");
			builder.put(grammarAccess.getAddEntityAccess().getGroup_5_2(), "rule__AddEntity__Group_5_2__0");
			builder.put(grammarAccess.getAddEntityAccess().getGroup_5_2_1(), "rule__AddEntity__Group_5_2_1__0");
			builder.put(grammarAccess.getAddEntityAccess().getGroup_6(), "rule__AddEntity__Group_6__0");
			builder.put(grammarAccess.getAddEntityAccess().getGroup_6_2(), "rule__AddEntity__Group_6_2__0");
			builder.put(grammarAccess.getAddEntityAccess().getGroup_6_2_1(), "rule__AddEntity__Group_6_2_1__0");
			builder.put(grammarAccess.getRenameEntityAccess().getGroup(), "rule__RenameEntity__Group__0");
			builder.put(grammarAccess.getRemoveEntityAccess().getGroup(), "rule__RemoveEntity__Group__0");
			builder.put(grammarAccess.getSplitEntityAccess().getGroup(), "rule__SplitEntity__Group__0");
			builder.put(grammarAccess.getMigrateEntityAccess().getGroup(), "rule__MigrateEntity__Group__0");
			builder.put(grammarAccess.getSplitEntityVerticalAccess().getGroup(), "rule__SplitEntityVertical__Group__0");
			builder.put(grammarAccess.getSplitEntityVerticalAccess().getGroup_8(), "rule__SplitEntityVertical__Group_8__0");
			builder.put(grammarAccess.getSplitEntityVerticalAccess().getGroup_8_1(), "rule__SplitEntityVertical__Group_8_1__0");
			builder.put(grammarAccess.getSplitEntityHorizontalAccess().getGroup(), "rule__SplitEntityHorizontal__Group__0");
			builder.put(grammarAccess.getMergeEntityAccess().getGroup(), "rule__MergeEntity__Group__0");
			builder.put(grammarAccess.getRenameAttributeAccess().getGroup(), "rule__RenameAttribute__Group__0");
			builder.put(grammarAccess.getRemoveAttributeAccess().getGroup(), "rule__RemoveAttribute__Group__0");
			builder.put(grammarAccess.getAddRelationAccess().getGroup(), "rule__AddRelation__Group__0");
			builder.put(grammarAccess.getAddRelationAccess().getGroup_0(), "rule__AddRelation__Group_0__0");
			builder.put(grammarAccess.getAddRelationAccess().getGroup_9(), "rule__AddRelation__Group_9__0");
			builder.put(grammarAccess.getAddRelationAccess().getGroup_10(), "rule__AddRelation__Group_10__0");
			builder.put(grammarAccess.getRenameRelationAccess().getGroup(), "rule__RenameRelation__Group__0");
			builder.put(grammarAccess.getRemoveRelationAccess().getGroup(), "rule__RemoveRelation__Group__0");
			builder.put(grammarAccess.getChangeRelationContainementAccess().getGroup(), "rule__ChangeRelationContainement__Group__0");
			builder.put(grammarAccess.getChangeRelationCardinalityAccess().getGroup(), "rule__ChangeRelationCardinality__Group__0");
			builder.put(grammarAccess.getEnableRelationContainmentAccess().getGroup(), "rule__EnableRelationContainment__Group__0");
			builder.put(grammarAccess.getDisableRelationContainmentAccess().getGroup(), "rule__DisableRelationContainment__Group__0");
			builder.put(grammarAccess.getEnableBidirectionalRelationAccess().getGroup(), "rule__EnableBidirectionalRelation__Group__0");
			builder.put(grammarAccess.getDisableBidirectionalRelationAccess().getGroup(), "rule__DisableBidirectionalRelation__Group__0");
			builder.put(grammarAccess.getAddAttributesToIndexAccess().getGroup(), "rule__AddAttributesToIndex__Group__0");
			builder.put(grammarAccess.getAddAttributesToIndexAccess().getGroup_5(), "rule__AddAttributesToIndex__Group_5__0");
			builder.put(grammarAccess.getRemoveAttributesToIndexAccess().getGroup(), "rule__RemoveAttributesToIndex__Group__0");
			builder.put(grammarAccess.getRemoveAttributesToIndexAccess().getGroup_5(), "rule__RemoveAttributesToIndex__Group_5__0");
			builder.put(grammarAccess.getRenameTableAccess().getGroup(), "rule__RenameTable__Group__0");
			builder.put(grammarAccess.getDropIndexTableAccess().getGroup(), "rule__DropIndexTable__Group__0");
			builder.put(grammarAccess.getAddIndexTableAccess().getGroup(), "rule__AddIndexTable__Group__0");
			builder.put(grammarAccess.getAddIndexTableAccess().getGroup_5(), "rule__AddIndexTable__Group_5__0");
			builder.put(grammarAccess.getAddIndexAccess().getGroup(), "rule__AddIndex__Group__0");
			builder.put(grammarAccess.getAddIndexAccess().getGroup_4(), "rule__AddIndex__Group_4__0");
			builder.put(grammarAccess.getAddIndexAccess().getGroup_4_3(), "rule__AddIndex__Group_4_3__0");
			builder.put(grammarAccess.getDropIndexAccess().getGroup(), "rule__DropIndex__Group__0");
			builder.put(grammarAccess.getAddGraphAttributeAccess().getGroup(), "rule__AddGraphAttribute__Group__0");
			builder.put(grammarAccess.getAddGraphAttributeAccess().getGroup_1(), "rule__AddGraphAttribute__Group_1__0");
			builder.put(grammarAccess.getAddGraphAttributeAccess().getGroup_5(), "rule__AddGraphAttribute__Group_5__0");
			builder.put(grammarAccess.getAddGraphEdgeAccess().getGroup(), "rule__AddGraphEdge__Group__0");
			builder.put(grammarAccess.getAddGraphEdgeAccess().getGroup_3(), "rule__AddGraphEdge__Group_3__0");
			builder.put(grammarAccess.getAddGraphEdgeAccess().getGroup_4(), "rule__AddGraphEdge__Group_4__0");
			builder.put(grammarAccess.getRemoveGraphAttributeAccess().getGroup(), "rule__RemoveGraphAttribute__Group__0");
			builder.put(grammarAccess.getRemoveGraphEdgeAccess().getGroup(), "rule__RemoveGraphEdge__Group__0");
			builder.put(grammarAccess.getRenabeGraphEdgeLabelAccess().getGroup(), "rule__RenabeGraphEdgeLabel__Group__0");
			builder.put(grammarAccess.getRenabeGraphEdgeLabelAccess().getGroup_2(), "rule__RenabeGraphEdgeLabel__Group_2__0");
			builder.put(grammarAccess.getAddCollectionIndexAccess().getGroup(), "rule__AddCollectionIndex__Group__0");
			builder.put(grammarAccess.getAddCollectionIndexAccess().getGroup_4(), "rule__AddCollectionIndex__Group_4__0");
			builder.put(grammarAccess.getAddCollectionIndexAccess().getGroup_4_3(), "rule__AddCollectionIndex__Group_4_3__0");
			builder.put(grammarAccess.getDropCollectionIndexAccess().getGroup(), "rule__DropCollectionIndex__Group__0");
			builder.put(grammarAccess.getRenameCollectionAccess().getGroup(), "rule__RenameCollection__Group__0");
			builder.put(grammarAccess.getModelAccess().getCustomDataTypesAssignment_1(), "rule__Model__CustomDataTypesAssignment_1");
			builder.put(grammarAccess.getModelAccess().getEntitiesAssignment_2(), "rule__Model__EntitiesAssignment_2");
			builder.put(grammarAccess.getModelAccess().getDatabasesAssignment_3(), "rule__Model__DatabasesAssignment_3");
			builder.put(grammarAccess.getModelAccess().getChangeOperatorsAssignment_4_2(), "rule__Model__ChangeOperatorsAssignment_4_2");
			builder.put(grammarAccess.getModelAccess().getChangeOperatorsAssignment_4_3_1(), "rule__Model__ChangeOperatorsAssignment_4_3_1");
			builder.put(grammarAccess.getStringTypeAccess().getMaxSizeAssignment_2_1(), "rule__StringType__MaxSizeAssignment_2_1");
			builder.put(grammarAccess.getFreetextTypeAccess().getTasksAssignment_2_1(), "rule__FreetextType__TasksAssignment_2_1");
			builder.put(grammarAccess.getFreetextTypeAccess().getTasksAssignment_2_2_1(), "rule__FreetextType__TasksAssignment_2_2_1");
			builder.put(grammarAccess.getNlpTaskAccess().getTypeAssignment_1(), "rule__NlpTask__TypeAssignment_1");
			builder.put(grammarAccess.getNlpTaskAccess().getWorkflowNameAssignment_3(), "rule__NlpTask__WorkflowNameAssignment_3");
			builder.put(grammarAccess.getCustomDataTypeAccess().getNameAssignment_2(), "rule__CustomDataType__NameAssignment_2");
			builder.put(grammarAccess.getCustomDataTypeAccess().getImplementationAssignment_4_1(), "rule__CustomDataType__ImplementationAssignment_4_1");
			builder.put(grammarAccess.getCustomDataTypeAccess().getElementsAssignment_5_0(), "rule__CustomDataType__ElementsAssignment_5_0");
			builder.put(grammarAccess.getCustomDataTypeAccess().getElementsAssignment_5_1_1(), "rule__CustomDataType__ElementsAssignment_5_1_1");
			builder.put(grammarAccess.getComplexDataTypeAccess().getImportedNamespaceAssignment_0_1(), "rule__ComplexDataType__ImportedNamespaceAssignment_0_1");
			builder.put(grammarAccess.getComplexDataTypeAccess().getNameAssignment_1(), "rule__ComplexDataType__NameAssignment_1");
			builder.put(grammarAccess.getComplexDataTypeAccess().getTypeAssignment_3(), "rule__ComplexDataType__TypeAssignment_3");
			builder.put(grammarAccess.getSimpleDataTypeAccess().getNameAssignment_1(), "rule__SimpleDataType__NameAssignment_1");
			builder.put(grammarAccess.getSimpleDataTypeAccess().getTypeAssignment_3(), "rule__SimpleDataType__TypeAssignment_3");
			builder.put(grammarAccess.getCustomDataTypeImplementationPackageAccess().getLocationAssignment_1(), "rule__CustomDataTypeImplementationPackage__LocationAssignment_1");
			builder.put(grammarAccess.getEntity_ImplAccess().getFunctionalTagsAssignment_0_2_0(), "rule__Entity_Impl__FunctionalTagsAssignment_0_2_0");
			builder.put(grammarAccess.getEntity_ImplAccess().getFunctionalTagsAssignment_0_2_1_1(), "rule__Entity_Impl__FunctionalTagsAssignment_0_2_1_1");
			builder.put(grammarAccess.getEntity_ImplAccess().getNfunctionalTagsAssignment_1_2_0(), "rule__Entity_Impl__NfunctionalTagsAssignment_1_2_0");
			builder.put(grammarAccess.getEntity_ImplAccess().getNfunctionalTagsAssignment_1_2_1_1(), "rule__Entity_Impl__NfunctionalTagsAssignment_1_2_1_1");
			builder.put(grammarAccess.getEntity_ImplAccess().getImportedNamespaceAssignment_2_1(), "rule__Entity_Impl__ImportedNamespaceAssignment_2_1");
			builder.put(grammarAccess.getEntity_ImplAccess().getNameAssignment_4(), "rule__Entity_Impl__NameAssignment_4");
			builder.put(grammarAccess.getEntity_ImplAccess().getAttributesAssignment_6_0(), "rule__Entity_Impl__AttributesAssignment_6_0");
			builder.put(grammarAccess.getEntity_ImplAccess().getAttributesAssignment_6_1(), "rule__Entity_Impl__AttributesAssignment_6_1");
			builder.put(grammarAccess.getEntity_ImplAccess().getRelationsAssignment_7_0(), "rule__Entity_Impl__RelationsAssignment_7_0");
			builder.put(grammarAccess.getEntity_ImplAccess().getRelationsAssignment_7_1(), "rule__Entity_Impl__RelationsAssignment_7_1");
			builder.put(grammarAccess.getFunctionalTag_ImplAccess().getNameAssignment(), "rule__FunctionalTag_Impl__NameAssignment");
			builder.put(grammarAccess.getNFunctionalTag_ImplAccess().getNameAssignment(), "rule__NFunctionalTag_Impl__NameAssignment");
			builder.put(grammarAccess.getAttribute_ImplAccess().getImportedNamespaceAssignment_1_1(), "rule__Attribute_Impl__ImportedNamespaceAssignment_1_1");
			builder.put(grammarAccess.getAttribute_ImplAccess().getNameAssignment_2(), "rule__Attribute_Impl__NameAssignment_2");
			builder.put(grammarAccess.getAttribute_ImplAccess().getTypeAssignment_4(), "rule__Attribute_Impl__TypeAssignment_4");
			builder.put(grammarAccess.getCustomAttributeAccess().getImportedNamespaceAssignment_1_1(), "rule__CustomAttribute__ImportedNamespaceAssignment_1_1");
			builder.put(grammarAccess.getCustomAttributeAccess().getNameAssignment_2(), "rule__CustomAttribute__NameAssignment_2");
			builder.put(grammarAccess.getCustomAttributeAccess().getTypeAssignment_4(), "rule__CustomAttribute__TypeAssignment_4");
			builder.put(grammarAccess.getRelation_ImplAccess().getImportedNamespaceAssignment_0_1(), "rule__Relation_Impl__ImportedNamespaceAssignment_0_1");
			builder.put(grammarAccess.getRelation_ImplAccess().getNameAssignment_1(), "rule__Relation_Impl__NameAssignment_1");
			builder.put(grammarAccess.getRelation_ImplAccess().getIsContainmentAssignment_2(), "rule__Relation_Impl__IsContainmentAssignment_2");
			builder.put(grammarAccess.getRelation_ImplAccess().getTypeAssignment_4(), "rule__Relation_Impl__TypeAssignment_4");
			builder.put(grammarAccess.getRelation_ImplAccess().getOppositeAssignment_5_1(), "rule__Relation_Impl__OppositeAssignment_5_1");
			builder.put(grammarAccess.getRelation_ImplAccess().getCardinalityAssignment_6_1(), "rule__Relation_Impl__CardinalityAssignment_6_1");
			builder.put(grammarAccess.getTableAccess().getImportedNamespaceAssignment_0_1(), "rule__Table__ImportedNamespaceAssignment_0_1");
			builder.put(grammarAccess.getTableAccess().getNameAssignment_3(), "rule__Table__NameAssignment_3");
			builder.put(grammarAccess.getTableAccess().getEntityAssignment_5(), "rule__Table__EntityAssignment_5");
			builder.put(grammarAccess.getTableAccess().getDbAssignment_6_1(), "rule__Table__DbAssignment_6_1");
			builder.put(grammarAccess.getTableAccess().getIndexSpecAssignment_7(), "rule__Table__IndexSpecAssignment_7");
			builder.put(grammarAccess.getTableAccess().getIdSpecAssignment_8(), "rule__Table__IdSpecAssignment_8");
			builder.put(grammarAccess.getCollectionAccess().getImportedNamespaceAssignment_0_1(), "rule__Collection__ImportedNamespaceAssignment_0_1");
			builder.put(grammarAccess.getCollectionAccess().getNameAssignment_1(), "rule__Collection__NameAssignment_1");
			builder.put(grammarAccess.getCollectionAccess().getEntityAssignment_3(), "rule__Collection__EntityAssignment_3");
			builder.put(grammarAccess.getKeyValueElementAccess().getImportedNamespaceAssignment_0_1(), "rule__KeyValueElement__ImportedNamespaceAssignment_0_1");
			builder.put(grammarAccess.getKeyValueElementAccess().getNameAssignment_1(), "rule__KeyValueElement__NameAssignment_1");
			builder.put(grammarAccess.getKeyValueElementAccess().getKeyAssignment_3(), "rule__KeyValueElement__KeyAssignment_3");
			builder.put(grammarAccess.getKeyValueElementAccess().getValuesAssignment_6_0(), "rule__KeyValueElement__ValuesAssignment_6_0");
			builder.put(grammarAccess.getKeyValueElementAccess().getValuesAssignment_6_1_1(), "rule__KeyValueElement__ValuesAssignment_6_1_1");
			builder.put(grammarAccess.getGraphNodeAccess().getImportedNamespaceAssignment_0_1(), "rule__GraphNode__ImportedNamespaceAssignment_0_1");
			builder.put(grammarAccess.getGraphNodeAccess().getNameAssignment_2(), "rule__GraphNode__NameAssignment_2");
			builder.put(grammarAccess.getGraphNodeAccess().getEntityAssignment_4(), "rule__GraphNode__EntityAssignment_4");
			builder.put(grammarAccess.getGraphNodeAccess().getAttributesAssignment_5_1(), "rule__GraphNode__AttributesAssignment_5_1");
			builder.put(grammarAccess.getGraphNodeAccess().getAttributesAssignment_5_2_1(), "rule__GraphNode__AttributesAssignment_5_2_1");
			builder.put(grammarAccess.getColumnAccess().getImportedNamespaceAssignment_0_1(), "rule__Column__ImportedNamespaceAssignment_0_1");
			builder.put(grammarAccess.getColumnAccess().getNameAssignment_2(), "rule__Column__NameAssignment_2");
			builder.put(grammarAccess.getColumnAccess().getEntityAssignment_5(), "rule__Column__EntityAssignment_5");
			builder.put(grammarAccess.getColumnAccess().getAttributesAssignment_6_2(), "rule__Column__AttributesAssignment_6_2");
			builder.put(grammarAccess.getColumnAccess().getAttributesAssignment_6_3_1(), "rule__Column__AttributesAssignment_6_3_1");
			builder.put(grammarAccess.getIndexSpecAccess().getImportedNamespaceAssignment_1_1(), "rule__IndexSpec__ImportedNamespaceAssignment_1_1");
			builder.put(grammarAccess.getIndexSpecAccess().getNameAssignment_3(), "rule__IndexSpec__NameAssignment_3");
			builder.put(grammarAccess.getIndexSpecAccess().getAttributesAssignment_5_2(), "rule__IndexSpec__AttributesAssignment_5_2");
			builder.put(grammarAccess.getIndexSpecAccess().getAttributesAssignment_5_3_1(), "rule__IndexSpec__AttributesAssignment_5_3_1");
			builder.put(grammarAccess.getIndexSpecAccess().getReferencesAssignment_6_2(), "rule__IndexSpec__ReferencesAssignment_6_2");
			builder.put(grammarAccess.getIndexSpecAccess().getReferencesAssignment_6_3_1(), "rule__IndexSpec__ReferencesAssignment_6_3_1");
			builder.put(grammarAccess.getIdSpecAccess().getAttributesAssignment_2_1(), "rule__IdSpec__AttributesAssignment_2_1");
			builder.put(grammarAccess.getIdSpecAccess().getAttributesAssignment_2_2_1(), "rule__IdSpec__AttributesAssignment_2_2_1");
			builder.put(grammarAccess.getRelationalDBAccess().getImportedNamespaceAssignment_1_1(), "rule__RelationalDB__ImportedNamespaceAssignment_1_1");
			builder.put(grammarAccess.getRelationalDBAccess().getNameAssignment_3(), "rule__RelationalDB__NameAssignment_3");
			builder.put(grammarAccess.getRelationalDBAccess().getTablesAssignment_5_2(), "rule__RelationalDB__TablesAssignment_5_2");
			builder.put(grammarAccess.getRelationalDBAccess().getTablesAssignment_5_3(), "rule__RelationalDB__TablesAssignment_5_3");
			builder.put(grammarAccess.getDocumentDBAccess().getImportedNamespaceAssignment_1_1(), "rule__DocumentDB__ImportedNamespaceAssignment_1_1");
			builder.put(grammarAccess.getDocumentDBAccess().getNameAssignment_3(), "rule__DocumentDB__NameAssignment_3");
			builder.put(grammarAccess.getDocumentDBAccess().getCollectionsAssignment_5_2(), "rule__DocumentDB__CollectionsAssignment_5_2");
			builder.put(grammarAccess.getDocumentDBAccess().getCollectionsAssignment_5_3(), "rule__DocumentDB__CollectionsAssignment_5_3");
			builder.put(grammarAccess.getKeyValueDBAccess().getImportedNamespaceAssignment_1_1(), "rule__KeyValueDB__ImportedNamespaceAssignment_1_1");
			builder.put(grammarAccess.getKeyValueDBAccess().getNameAssignment_3(), "rule__KeyValueDB__NameAssignment_3");
			builder.put(grammarAccess.getKeyValueDBAccess().getElementsAssignment_5_2(), "rule__KeyValueDB__ElementsAssignment_5_2");
			builder.put(grammarAccess.getKeyValueDBAccess().getElementsAssignment_5_3_1(), "rule__KeyValueDB__ElementsAssignment_5_3_1");
			builder.put(grammarAccess.getGraphDBAccess().getImportedNamespaceAssignment_1_1(), "rule__GraphDB__ImportedNamespaceAssignment_1_1");
			builder.put(grammarAccess.getGraphDBAccess().getNameAssignment_3(), "rule__GraphDB__NameAssignment_3");
			builder.put(grammarAccess.getGraphDBAccess().getEdgesAssignment_5_2(), "rule__GraphDB__EdgesAssignment_5_2");
			builder.put(grammarAccess.getGraphDBAccess().getEdgesAssignment_5_3_1(), "rule__GraphDB__EdgesAssignment_5_3_1");
			builder.put(grammarAccess.getColumnDBAccess().getImportedNamespaceAssignment_1_1(), "rule__ColumnDB__ImportedNamespaceAssignment_1_1");
			builder.put(grammarAccess.getColumnDBAccess().getNameAssignment_3(), "rule__ColumnDB__NameAssignment_3");
			builder.put(grammarAccess.getColumnDBAccess().getColumnsAssignment_5_2(), "rule__ColumnDB__ColumnsAssignment_5_2");
			builder.put(grammarAccess.getColumnDBAccess().getColumnsAssignment_5_3_1(), "rule__ColumnDB__ColumnsAssignment_5_3_1");
			builder.put(grammarAccess.getGraphEdge_ImplAccess().getEntityAssignment_2(), "rule__GraphEdge_Impl__EntityAssignment_2");
			builder.put(grammarAccess.getGraphEdge_ImplAccess().getFromAssignment_4_1(), "rule__GraphEdge_Impl__FromAssignment_4_1");
			builder.put(grammarAccess.getGraphEdge_ImplAccess().getToAssignment_5_1(), "rule__GraphEdge_Impl__ToAssignment_5_1");
			builder.put(grammarAccess.getGraphEdgeLabelAccess().getImportedNamespaceAssignment_1_1(), "rule__GraphEdgeLabel__ImportedNamespaceAssignment_1_1");
			builder.put(grammarAccess.getGraphEdgeLabelAccess().getNameAssignment_2(), "rule__GraphEdgeLabel__NameAssignment_2");
			builder.put(grammarAccess.getGraphEdgeLabelAccess().getTypeAssignment_4(), "rule__GraphEdgeLabel__TypeAssignment_4");
			builder.put(grammarAccess.getGraphAttribute_ImplAccess().getImportedNamespaceAssignment_1_1(), "rule__GraphAttribute_Impl__ImportedNamespaceAssignment_1_1");
			builder.put(grammarAccess.getGraphAttribute_ImplAccess().getNameAssignment_2(), "rule__GraphAttribute_Impl__NameAssignment_2");
			builder.put(grammarAccess.getGraphAttribute_ImplAccess().getValueAssignment_4(), "rule__GraphAttribute_Impl__ValueAssignment_4");
			builder.put(grammarAccess.getAddCustomDataTypeAttributeAccess().getNameAssignment_1(), "rule__AddCustomDataTypeAttribute__NameAssignment_1");
			builder.put(grammarAccess.getAddCustomDataTypeAttributeAccess().getImportedNamespaceAssignment_3_1(), "rule__AddCustomDataTypeAttribute__ImportedNamespaceAssignment_3_1");
			builder.put(grammarAccess.getAddCustomDataTypeAttributeAccess().getOwnerEntityAssignment_5(), "rule__AddCustomDataTypeAttribute__OwnerEntityAssignment_5");
			builder.put(grammarAccess.getAddCustomDataTypeAttributeAccess().getTypeAssignment_7(), "rule__AddCustomDataTypeAttribute__TypeAssignment_7");
			builder.put(grammarAccess.getChangePrimitiveDataTypeAttributeAccess().getMaxSizeAssignment_2_1(), "rule__ChangePrimitiveDataTypeAttribute__MaxSizeAssignment_2_1");
			builder.put(grammarAccess.getChangePrimitiveDataTypeAttributeAccess().getAttributeToChangeAssignment_4(), "rule__ChangePrimitiveDataTypeAttribute__AttributeToChangeAssignment_4");
			builder.put(grammarAccess.getChangeCustomDataTypeAttributeAccess().getAttributeToChangeAssignment_3(), "rule__ChangeCustomDataTypeAttribute__AttributeToChangeAssignment_3");
			builder.put(grammarAccess.getChangeCustomDataTypeAttributeAccess().getNewTypeAssignment_5(), "rule__ChangeCustomDataTypeAttribute__NewTypeAssignment_5");
			builder.put(grammarAccess.getAddEntityAccess().getImportedNamespaceAssignment_0_1(), "rule__AddEntity__ImportedNamespaceAssignment_0_1");
			builder.put(grammarAccess.getAddEntityAccess().getNameAssignment_3(), "rule__AddEntity__NameAssignment_3");
			builder.put(grammarAccess.getAddEntityAccess().getAttributesAssignment_5_2_0(), "rule__AddEntity__AttributesAssignment_5_2_0");
			builder.put(grammarAccess.getAddEntityAccess().getAttributesAssignment_5_2_1_1(), "rule__AddEntity__AttributesAssignment_5_2_1_1");
			builder.put(grammarAccess.getAddEntityAccess().getRelationsAssignment_6_2_0(), "rule__AddEntity__RelationsAssignment_6_2_0");
			builder.put(grammarAccess.getAddEntityAccess().getRelationsAssignment_6_2_1_1(), "rule__AddEntity__RelationsAssignment_6_2_1_1");
			builder.put(grammarAccess.getRenameEntityAccess().getEntityToRenameAssignment_2(), "rule__RenameEntity__EntityToRenameAssignment_2");
			builder.put(grammarAccess.getRenameEntityAccess().getNewEntityNameAssignment_4(), "rule__RenameEntity__NewEntityNameAssignment_4");
			builder.put(grammarAccess.getRemoveEntityAccess().getEntityToRemoveAssignment_2(), "rule__RemoveEntity__EntityToRemoveAssignment_2");
			builder.put(grammarAccess.getSplitEntityAccess().getEntityToBeSplitAssignment_3(), "rule__SplitEntity__EntityToBeSplitAssignment_3");
			builder.put(grammarAccess.getSplitEntityAccess().getFirstNewEntityAssignment_5(), "rule__SplitEntity__FirstNewEntityAssignment_5");
			builder.put(grammarAccess.getSplitEntityAccess().getSecondNewEntityAssignment_7(), "rule__SplitEntity__SecondNewEntityAssignment_7");
			builder.put(grammarAccess.getMigrateEntityAccess().getEntityAssignment_1(), "rule__MigrateEntity__EntityAssignment_1");
			builder.put(grammarAccess.getMigrateEntityAccess().getNewDatabaseAssignment_3(), "rule__MigrateEntity__NewDatabaseAssignment_3");
			builder.put(grammarAccess.getSplitEntityVerticalAccess().getEntity1Assignment_3(), "rule__SplitEntityVertical__Entity1Assignment_3");
			builder.put(grammarAccess.getSplitEntityVerticalAccess().getEntity2nameAssignment_5(), "rule__SplitEntityVertical__Entity2nameAssignment_5");
			builder.put(grammarAccess.getSplitEntityVerticalAccess().getAttributeListAssignment_8_0(), "rule__SplitEntityVertical__AttributeListAssignment_8_0");
			builder.put(grammarAccess.getSplitEntityVerticalAccess().getAttributeListAssignment_8_1_1(), "rule__SplitEntityVertical__AttributeListAssignment_8_1_1");
			builder.put(grammarAccess.getSplitEntityHorizontalAccess().getEntity1Assignment_3(), "rule__SplitEntityHorizontal__Entity1Assignment_3");
			builder.put(grammarAccess.getSplitEntityHorizontalAccess().getEntity2nameAssignment_5(), "rule__SplitEntityHorizontal__Entity2nameAssignment_5");
			builder.put(grammarAccess.getSplitEntityHorizontalAccess().getAttributeAssignment_7(), "rule__SplitEntityHorizontal__AttributeAssignment_7");
			builder.put(grammarAccess.getSplitEntityHorizontalAccess().getExpressionAssignment_9(), "rule__SplitEntityHorizontal__ExpressionAssignment_9");
			builder.put(grammarAccess.getMergeEntityAccess().getFirstEntityToMergeAssignment_2(), "rule__MergeEntity__FirstEntityToMergeAssignment_2");
			builder.put(grammarAccess.getMergeEntityAccess().getSecondEntityToMergeAssignment_3(), "rule__MergeEntity__SecondEntityToMergeAssignment_3");
			builder.put(grammarAccess.getMergeEntityAccess().getNewEntityNameAssignment_5(), "rule__MergeEntity__NewEntityNameAssignment_5");
			builder.put(grammarAccess.getRenameAttributeAccess().getAttributeToRenameAssignment_2(), "rule__RenameAttribute__AttributeToRenameAssignment_2");
			builder.put(grammarAccess.getRenameAttributeAccess().getNewNameAssignment_4(), "rule__RenameAttribute__NewNameAssignment_4");
			builder.put(grammarAccess.getRemoveAttributeAccess().getAttributeToRemoveAssignment_2(), "rule__RemoveAttribute__AttributeToRemoveAssignment_2");
			builder.put(grammarAccess.getAddRelationAccess().getImportedNamespaceAssignment_0_1(), "rule__AddRelation__ImportedNamespaceAssignment_0_1");
			builder.put(grammarAccess.getAddRelationAccess().getNameAssignment_3(), "rule__AddRelation__NameAssignment_3");
			builder.put(grammarAccess.getAddRelationAccess().getOwnerEntityAssignment_5(), "rule__AddRelation__OwnerEntityAssignment_5");
			builder.put(grammarAccess.getAddRelationAccess().getIsContainmentAssignment_6(), "rule__AddRelation__IsContainmentAssignment_6");
			builder.put(grammarAccess.getAddRelationAccess().getTypeAssignment_8(), "rule__AddRelation__TypeAssignment_8");
			builder.put(grammarAccess.getAddRelationAccess().getOppositeAssignment_9_1(), "rule__AddRelation__OppositeAssignment_9_1");
			builder.put(grammarAccess.getAddRelationAccess().getCardinalityAssignment_10_1(), "rule__AddRelation__CardinalityAssignment_10_1");
			builder.put(grammarAccess.getRenameRelationAccess().getRelationToRenameAssignment_2(), "rule__RenameRelation__RelationToRenameAssignment_2");
			builder.put(grammarAccess.getRenameRelationAccess().getNewRelationNameAssignment_4(), "rule__RenameRelation__NewRelationNameAssignment_4");
			builder.put(grammarAccess.getRemoveRelationAccess().getRelationToRemoveAssignment_2(), "rule__RemoveRelation__RelationToRemoveAssignment_2");
			builder.put(grammarAccess.getChangeRelationContainementAccess().getRelationAssignment_2(), "rule__ChangeRelationContainement__RelationAssignment_2");
			builder.put(grammarAccess.getChangeRelationContainementAccess().getNewContainmentAssignment_4(), "rule__ChangeRelationContainement__NewContainmentAssignment_4");
			builder.put(grammarAccess.getChangeRelationCardinalityAccess().getRelationAssignment_2(), "rule__ChangeRelationCardinality__RelationAssignment_2");
			builder.put(grammarAccess.getChangeRelationCardinalityAccess().getNewCardinalityAssignment_4(), "rule__ChangeRelationCardinality__NewCardinalityAssignment_4");
			builder.put(grammarAccess.getEnableRelationContainmentAccess().getRelationAssignment_3(), "rule__EnableRelationContainment__RelationAssignment_3");
			builder.put(grammarAccess.getDisableRelationContainmentAccess().getRelationAssignment_3(), "rule__DisableRelationContainment__RelationAssignment_3");
			builder.put(grammarAccess.getEnableBidirectionalRelationAccess().getRelationAssignment_3(), "rule__EnableBidirectionalRelation__RelationAssignment_3");
			builder.put(grammarAccess.getDisableBidirectionalRelationAccess().getRelationAssignment_3(), "rule__DisableBidirectionalRelation__RelationAssignment_3");
			builder.put(grammarAccess.getAddAttributesToIndexAccess().getTableAssignment_2(), "rule__AddAttributesToIndex__TableAssignment_2");
			builder.put(grammarAccess.getAddAttributesToIndexAccess().getAttributesAssignment_4(), "rule__AddAttributesToIndex__AttributesAssignment_4");
			builder.put(grammarAccess.getAddAttributesToIndexAccess().getAttributesAssignment_5_1(), "rule__AddAttributesToIndex__AttributesAssignment_5_1");
			builder.put(grammarAccess.getRemoveAttributesToIndexAccess().getTableAssignment_2(), "rule__RemoveAttributesToIndex__TableAssignment_2");
			builder.put(grammarAccess.getRemoveAttributesToIndexAccess().getAttributesAssignment_4(), "rule__RemoveAttributesToIndex__AttributesAssignment_4");
			builder.put(grammarAccess.getRemoveAttributesToIndexAccess().getAttributesAssignment_5_1(), "rule__RemoveAttributesToIndex__AttributesAssignment_5_1");
			builder.put(grammarAccess.getRenameTableAccess().getTableToRenameAssignment_2(), "rule__RenameTable__TableToRenameAssignment_2");
			builder.put(grammarAccess.getRenameTableAccess().getNewNameAssignment_4(), "rule__RenameTable__NewNameAssignment_4");
			builder.put(grammarAccess.getDropIndexTableAccess().getTableAssignment_2(), "rule__DropIndexTable__TableAssignment_2");
			builder.put(grammarAccess.getAddIndexTableAccess().getTableAssignment_2(), "rule__AddIndexTable__TableAssignment_2");
			builder.put(grammarAccess.getAddIndexTableAccess().getAttributesAssignment_4(), "rule__AddIndexTable__AttributesAssignment_4");
			builder.put(grammarAccess.getAddIndexTableAccess().getAttributesAssignment_5_1(), "rule__AddIndexTable__AttributesAssignment_5_1");
			builder.put(grammarAccess.getAddIndexAccess().getTableAssignment_3(), "rule__AddIndex__TableAssignment_3");
			builder.put(grammarAccess.getAddIndexAccess().getAttributesAssignment_4_2(), "rule__AddIndex__AttributesAssignment_4_2");
			builder.put(grammarAccess.getAddIndexAccess().getAttributesAssignment_4_3_1(), "rule__AddIndex__AttributesAssignment_4_3_1");
			builder.put(grammarAccess.getDropIndexAccess().getTableAssignment_3(), "rule__DropIndex__TableAssignment_3");
			builder.put(grammarAccess.getAddGraphAttributeAccess().getImportedNamespaceAssignment_1_1(), "rule__AddGraphAttribute__ImportedNamespaceAssignment_1_1");
			builder.put(grammarAccess.getAddGraphAttributeAccess().getNameAssignment_3(), "rule__AddGraphAttribute__NameAssignment_3");
			builder.put(grammarAccess.getAddGraphAttributeAccess().getValueAssignment_5_1(), "rule__AddGraphAttribute__ValueAssignment_5_1");
			builder.put(grammarAccess.getAddGraphEdgeAccess().getFromAssignment_3_1(), "rule__AddGraphEdge__FromAssignment_3_1");
			builder.put(grammarAccess.getAddGraphEdgeAccess().getToAssignment_4_1(), "rule__AddGraphEdge__ToAssignment_4_1");
			builder.put(grammarAccess.getRemoveGraphAttributeAccess().getNodeAssignment_3(), "rule__RemoveGraphAttribute__NodeAssignment_3");
			builder.put(grammarAccess.getRemoveGraphEdgeAccess().getGraphEdgeToRemoveAssignment_3(), "rule__RemoveGraphEdge__GraphEdgeToRemoveAssignment_3");
			builder.put(grammarAccess.getRenabeGraphEdgeLabelAccess().getNewNameAssignment_2_1(), "rule__RenabeGraphEdgeLabel__NewNameAssignment_2_1");
			builder.put(grammarAccess.getRenabeGraphEdgeLabelAccess().getEdgeAssignment_4(), "rule__RenabeGraphEdgeLabel__EdgeAssignment_4");
			builder.put(grammarAccess.getAddCollectionIndexAccess().getCollectionAssignment_3(), "rule__AddCollectionIndex__CollectionAssignment_3");
			builder.put(grammarAccess.getAddCollectionIndexAccess().getAttributesAssignment_4_2(), "rule__AddCollectionIndex__AttributesAssignment_4_2");
			builder.put(grammarAccess.getAddCollectionIndexAccess().getAttributesAssignment_4_3_1(), "rule__AddCollectionIndex__AttributesAssignment_4_3_1");
			builder.put(grammarAccess.getDropCollectionIndexAccess().getCollectionAssignment_3(), "rule__DropCollectionIndex__CollectionAssignment_3");
			builder.put(grammarAccess.getRenameCollectionAccess().getCollectionToRenameAssignment_2(), "rule__RenameCollection__CollectionToRenameAssignment_2");
			builder.put(grammarAccess.getRenameCollectionAccess().getNewNameAssignment_4(), "rule__RenameCollection__NewNameAssignment_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TyphonMLGrammarAccess grammarAccess;

	@Override
	protected InternalTyphonMLParser createParser() {
		InternalTyphonMLParser result = new InternalTyphonMLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TyphonMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TyphonMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
