/*
 * generated by Xtext 2.14.0
 */
package org.typhon.dsls.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.typhon.dsls.xtext.typhonml.ui.internal.TyphonmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TyphonMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TyphonmlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TyphonmlActivator activator = TyphonmlActivator.getInstance();
		return activator != null ? activator.getInjector(TyphonmlActivator.ORG_TYPHON_DSLS_XTEXT_TYPHONML) : null;
	}

}
