/*
 * generated by Xtext 2.15.0
 */
package it.univaq.disim.typhon.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TyphonMLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/univaq/disim/typhon/parser/antlr/internal/InternalTyphonML.tokens");
	}
}
