/**
 * generated by Xtext 2.15.0
 */
package it.univaq.disim.typhon.validation;

import it.univaq.disim.typhon.validation.AbstractTyphonMLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TyphonMLValidator extends AbstractTyphonMLValidator {
}
