<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="typhonml" nsURI="http://org.typhon.dsls.typhonml.sirius" nsPrefix="typhonml">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="databases" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Database"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//DataType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Database" abstract="true" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveDataType" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="CustomDataType" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//DataTypeItem"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeItem" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Attribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Relation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericList" lowerBound="1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//GenericList"
        eOpposite="/it.univaq.disim.typhonml/model/typhonml.ecore#//GenericList/entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" eType="ecore:EEnum /it.univaq.disim.typhonml/model/typhonml.ecore#//Cardinality"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Relation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isContainment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalDB" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//Database">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Table"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//NamedElement /it.univaq.disim.typhonml/model/typhonml.ecore#//GenericList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexSpec" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//IndexSpec"
        containment="true" eOpposite="/it.univaq.disim.typhonml/model/typhonml.ecore#//IndexSpec/table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idSpec" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//IdSpec"
        containment="true" eOpposite="/it.univaq.disim.typhonml/model/typhonml.ecore#//IdSpec/table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="db" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Database"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexSpec" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Relation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Table"
        eOpposite="/it.univaq.disim.typhonml/model/typhonml.ecore#//Table/indexSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Table"
        eOpposite="/it.univaq.disim.typhonml/model/typhonml.ecore#//Table/idSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentDB" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//Database">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collections" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Collection"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collection" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//GenericList /it.univaq.disim.typhonml/model/typhonml.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="KeyValueDB" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//Database">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//KeyValueElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyValueElement" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//GenericList">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphDB" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//Database">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//GraphNode"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//GraphEdge"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphNode" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//NamedElement /it.univaq.disim.typhonml/model/typhonml.ecore#//GenericList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//GraphAttribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphAttribute" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphEdge" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//GraphNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//GraphNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labels" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//GraphEdgeLabel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphEdgeLabel" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnDB" eSuperTypes="/it.univaq.disim.typhonml/model/typhonml.ecore#//Database">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Column"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Cardinality">
    <eLiterals name="zero_one"/>
    <eLiterals name="one" value="1"/>
    <eLiterals name="zero_many" value="2"/>
    <eLiterals name="one_many" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="ecore:EClass /it.univaq.disim.typhonml/model/typhonml.ecore#//Entity"
        eOpposite="/it.univaq.disim.typhonml/model/typhonml.ecore#//Entity/genericList"/>
  </eClassifiers>
</ecore:EPackage>
